#import "Localization.h"

#import "ConfigSupport.h"

NSString *ConfiguredLanguage(void) {
    NSString *value = [GDTReadConfigDictionary()[@"GDRIVE_BACKUP_LANG"] ?: @"" lowercaseString];
    for (NSString *code in SupportedLanguageCodes()) {
        if ([value isEqualToString:code] || [value hasPrefix:[code stringByAppendingString:@"-"]] || [value hasPrefix:[code stringByAppendingString:@"_"]]) {
            return code;
        }
    }
    if ([value hasPrefix:@"zh-hk"] || [value hasPrefix:@"zh_hk"] || [value hasPrefix:@"zh-hant-hk"] || [value hasPrefix:@"zh_hant_hk"] || [value hasPrefix:@"zh-mo"] || [value hasPrefix:@"zh_mo"]) {
        return @"yue";
    }

    NSString *preferred = NSLocale.preferredLanguages.firstObject.lowercaseString;
    if ([preferred hasPrefix:@"de"]) return @"de";
    if ([preferred hasPrefix:@"fr"]) return @"fr";
    if ([preferred hasPrefix:@"es"]) return @"es";
    if ([preferred hasPrefix:@"ja"]) return @"ja";
    if ([preferred hasPrefix:@"ko"]) return @"ko";
    if ([preferred hasPrefix:@"yue"] || [preferred hasPrefix:@"zh-hk"] || [preferred hasPrefix:@"zh_hk"] || [preferred hasPrefix:@"zh-hant-hk"] || [preferred hasPrefix:@"zh_hant_hk"] || [preferred hasPrefix:@"zh-mo"] || [preferred hasPrefix:@"zh_mo"]) return @"yue";
    return @"en";
}

NSString *T(NSString *language, NSString *key) {
    NSDictionary<NSString *, NSString *> *de = @{
        @"confirmTarget": @"Dieses Volume verwenden?",
        @"startBackup": @"Backup starten",
        @"notNow": @"Nicht jetzt",
        @"running": @"Sicherung wird erstellt ...",
        @"completed": @"Sicherung abgeschlossen.",
        @"runningHint": @"Bitte Festplatte nicht auswerfen.",
        @"completedHint": @"Backup ist fertig.",
        @"backupProgress": @"Sicherungsfortschritt",
        @"cancelBackup": @"Backup abbrechen …",
        @"cancelBackupConfirm": @"Backup wirklich abbrechen?",
        @"cancelBackupDetail": @"Der laufende Kopiervorgang wird beendet. Vorhandene Sicherungen bleiben erhalten.",
        @"cancelBackupAction": @"Backup abbrechen",
        @"cancellingBackup": @"Backup wird abgebrochen …",
        @"failed": @"Sicherung fehlgeschlagen.",
        @"failedHint": @"Keine vollständige Sicherung erstellt. Protokoll prüfen.",
        @"failedPermissionHint": @"Ziel nicht beschreibbar. NAS-Zugriffsrechte prüfen.",
        @"failedNASConnectionHint": @"NAS-Verbindung wurde getrennt. NAS erneut verbinden und Backup wiederholen.",
        @"notifyBackupFailures": @"Bei Fehlern automatischer Backups benachrichtigen",
        @"notifyBackupSuccesses": @"Auch erfolgreiche automatische Backups melden",
        @"backupNotificationSuccessTitle": @"Backup erfolgreich fertiggestellt",
        @"backupNotificationSuccessBody": @"Das automatische Backup wurde erfolgreich abgeschlossen.",
        @"backupNotificationRecoverySuccessBody": @"Ein späteres automatisches Backup wurde erfolgreich abgeschlossen. Ihr Backup ist wieder aktuell.",
        @"backupNotificationRetrySuccessBody": @"Der automatische Wiederholungsversuch wurde erfolgreich abgeschlossen. Ihr Backup ist wieder aktuell.",
        @"backupNotificationFailureTitle": @"Automatisches Backup fehlgeschlagen",
        @"backupNotificationMissedTitle": @"Tägliches Backup fehlt",
        @"backupNotificationMissedBody": @"Das für 20:00 Uhr geplante Backup wurde bis 21:00 Uhr nicht erfolgreich abgeschlossen.",
        @"backupNotificationTargetUnavailable": @"Das Backup-Ziel ist nicht verfügbar. Bitte verbinden und Backup erneut starten.",
        @"backupNotificationNASRetryBody": @"Das NAS ist noch nicht vollständig bereit. Ein neuer Versuch startet automatisch in 30 Minuten.",
        @"backupNotificationRetryRunningTitle": @"Automatischer Wiederholungsversuch läuft",
        @"backupNotificationRetryRunningBody": @"GDrive wird erneut gesichert. Öffne GDrive Backup Tiger, um den Fortschritt zu sehen.",
        @"backupNotificationRetryFailureBody": @"Auch der automatische Wiederholungsversuch ist fehlgeschlagen. Bitte NAS-Verbindung prüfen und das Backup erneut starten.",
        @"unknownExternalVolumeTitle": @"Neue Festplatte erkannt",
        @"unknownExternalVolumeBody": @"„%@“ wird nicht verwendet. Kein Backup wurde gestartet.",
        @"unknownExternalVolumeSetupAction": @"Als Backup-Ziel einrichten",
        @"unknownExternalVolumeIgnoreAction": @"Ignorieren",
        @"unknownExternalVolumeReviewSetup": @"„%@“ ist nur vorgemerkt. „Speichern“ registriert sie für Backups über eine externe Platte; das aktuell ausgewählte Hauptziel bleibt unverändert.",
        @"unknownExternalVolumeUnavailable": @"Die Festplatte ist nicht mehr verfügbar. Es wurde nichts geändert.",
        @"unknownExternalVolumeUnsupported": @"Als Backup-Ziel wird ein beschreibbares APFS-Volume benötigt. Es wurde nichts geändert.",
        @"unknownExternalVolumeChooseTitle": @"Backup-Volume auswählen",
        @"unknownExternalVolumeChooseBody": @"Diese Festplatte enthält mehrere geeignete APFS-Volumes. Wähle ausdrücklich das Volume, das vorgemerkt werden soll.",
        @"unknownExternalVolumeChooseAction": @"Volume auswählen",
        @"unknownExternalVolumeChoosePlaceholder": @"Bitte Volume auswählen …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — eingehängt als „%2$@“",
        @"restoreTitle": @"Dateien wiederherstellen",
        @"restoreSubtitle": @"Aktuelle und tatsächlich vorhandene ältere Kopien",
        @"restoreFilesColumn": @"Dateien und Ordner",
        @"restoreVersionsColumn": @"Verfügbare Version",
        @"restoreSizeColumn": @"Größe",
        @"restoreBack": @"Zurück",
        @"restoreOpenFolder": @"Ordner öffnen",
        @"restoreAction": @"Wiederherstellen …",
        @"restoreLoading": @"Backup wird gelesen …",
        @"restoreEmpty": @"In diesem Ordner wurden keine wiederherstellbaren Dateien gefunden.",
        @"restoreTargetUnavailable": @"Backup-Ziel nicht verfügbar. Bitte verbinden und erneut versuchen.",
        @"restoreCurrent": @"Aktuelle Sicherung",
        @"restoreHistorical": @"Ältere Kopie",
        @"restoreVerified": @"Wiederhergestellt und mit SHA-256 geprüft.",
        @"restoreIntegrityFailed": @"Wiederherstellung konnte nicht sicher geprüft werden.",
        @"restoreFailed": @"Datei konnte nicht wiederhergestellt werden. Ziel und Backup bitte prüfen.",
        @"restoreShowInFinder": @"Im Finder zeigen",
        @"restoreNoVersions": @"Für diese Datei ist keine sichere Kopie verfügbar.",
        @"restoreChooseDestination": @"Ordner für die wiederhergestellte Datei wählen.",
        @"cancelled": @"Sicherung abgebrochen.",
        @"cancelledHint": @"Es wurde kein erfolgreicher Abschluss bestätigt.",
        @"skipped": @"Keine neue Sicherung gestartet.",
        @"skippedHint": @"Eine Sicherung läuft bereits.",
        @"setupTitle": @"Backup-Ziel und Startmodus",
        @"targetType": @"App-/Zeitplan-Ziel",
        @"destinationPreview": @"Genaues Ziel",
        @"externalVolume": @"Externe Platte",
        @"encryptionLabel": @"Verschlüsselung",
        @"encryptionNone": @"Keine",
        @"encryptionAPFS": @"Verschlüsseltes APFS",
        @"encryptionAPFSTip": @"Die App liest oder speichert kein Passwort.",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"rclone verwaltet den Schlüssel; die App liest oder speichert kein Passwort.",
        @"cryptRemoteLabel": @"Crypt-Remote",
        @"nas": @"NAS / Netzwerk",
        @"mountedNas": @"Gemountete NAS",
        @"refresh": @"Aktualisieren",
        @"discover": @"Suchen",
        @"openFinder": @"Im Finder öffnen",
        @"nasUrl": @"NAS-URL",
        @"nasMount": @"Mountpunkt",
        @"nasSubdir": @"Zielordner",
        @"schedule": @"Starten",
        @"scheduleManual": @"Nur manuell",
        @"scheduleLogin": @"Beim Login",
        @"scheduleHourly": @"Stündlich",
        @"scheduleDaily": @"Täglich 20:00",
        @"save": @"Speichern",
        @"dryRun": @"Backup prüfen",
        @"dryRunRunning": @"Prüfung läuft …",
        @"backupNow": @"Backup jetzt",
        @"dryRunTip": @"Prüft Quelle und Ziel, ohne Dateien zu kopieren.",
        @"backupNowTip": @"Startet das echte Backup und schreibt auf das gewählte Ziel.",
        @"statusReady": @"Bereit.",
        @"statusSaved": @"Gespeichert.",
        @"statusSearching": @"Suche im Netzwerk ...",
        @"statusDiscoveryDone": @"Netzwerksuche abgeschlossen.",
        @"statusBackupStarted": @"Backup gestartet.",
        @"statusBackupPreparing": @"Backup wird vorbereitet …",
        @"statusDryRunStarted": @"Backup wird geprüft … Es wird nichts kopiert.",
        @"statusDryRunSucceeded": @"Prüfung abgeschlossen. Google Drive und Backup-Ziel sind erreichbar.",
        @"statusDryRunTargetUnavailable": @"Prüfung fehlgeschlagen: Backup-Ziel ist nicht verbunden.",
        @"statusDryRunFailed": @"Prüfung fehlgeschlagen. Details findest du in der Diagnose.",
        @"statusUnsavedChanges": @"Änderungen zuerst speichern. Es wurde kein Backup gestartet.",
        @"statusEncryptionIncompatible": @"Diese Verschlüsselung passt nicht zum gewählten Ziel.",
        @"statusCryptRemoteInvalid": @"Einen sicheren, vom Google-Drive-Remote verschiedenen Crypt-Remote-Namen eingeben.",
        @"setupCheckSectionTitle": @"Systemprüfung",
        @"setupCheckButton": @"Einrichtung prüfen",
        @"setupCheckRunning": @"Prüfung läuft …",
        @"setupCheckNotRun": @"Noch nicht geprüft.",
        @"setupCheckDependenciesLabel": @"Werkzeuge",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"Backup-Ziel",
        @"setupCheckDependenciesReady": @"Alle benötigten Werkzeuge sind installiert.",
        @"setupCheckDependenciesMissing": @"Fehlt: %@.",
        @"setupCheckRemoteBlocked": @"Erst die fehlenden Werkzeuge installieren.",
        @"setupCheckRemoteMissing": @"Der rclone-Remote ist nicht eingerichtet.",
        @"setupCheckRemoteReady": @"Google Drive ist erreichbar.",
        @"setupCheckRemoteUnavailable": @"Google Drive ist momentan nicht erreichbar.",
        @"setupCheckDestinationReady": @"Ziel ist eingebunden und zugänglich.",
        @"setupCheckDestinationUnavailable": @"Ziel ist nicht verfügbar oder nicht beschreibbar.",
        @"setupCheckEncryptedAPFSRequired": @"Verschlüsseltes, entsperrtes APFS-Ziel erforderlich.",
        @"setupCheckEncryptedAPFSReady": @"Verschlüsseltes APFS-Ziel ist bestätigt.",
        @"setupCheckRcloneCryptReady": @"rclone crypt schützt dieses Ziel vollständig.",
        @"setupCheckRcloneCryptInvalid": @"Crypt-Remote oder Verschlüsselungsoptionen bitte prüfen.",
        @"setupCheckReady": @"Einrichtung ist bereit.",
        @"setupCheckNeedsAttention": @"Einrichtung braucht Aufmerksamkeit.",
        @"selectMountedVolume": @"Volume auswählen",
        @"aboutMenu": @"Über GDrive Backup Tiger",
        @"settingsMenu": @"Einstellungen ...",
        @"hideMenu": @"GDrive Backup Tiger ausblenden",
        @"quitMenu": @"GDrive Backup Tiger beenden",
        @"settingsTitle": @"Einstellungen",
        @"languageSetting": @"Sprache",
        @"cancel": @"Abbrechen",
        @"done": @"Fertig",
        @"languageSaved": @"Sprache gespeichert.",
        @"overviewSubtitle": @"Unabhängige Kopie · klarer Status · bereit zum Wiederherstellen",
        @"overviewLastRun": @"Letztes Backup",
        @"overviewNextRun": @"Nächster Lauf",
        @"overviewTarget": @"Ziel",
        @"overviewStorage": @"Freier Zielspeicher",
        @"overviewSettings": @"Backup einrichten …",
        @"overviewOpen": @"GDrive Backup Tiger öffnen",
        @"overviewNeverRun": @"Noch kein Backup",
        @"overviewUnavailable": @"Nicht verfügbar",
        @"overviewFreeOf": @"%@ frei von %@",
        @"overviewStatusInterrupted": @"Sicherung wurde unterbrochen.",
        @"overviewStatusUnknown": @"Backup-Status unbekannt.",
        @"automaticBackupsPaused": @"Automatische Backups pausiert",
        @"pauseAutomaticBackups": @"Automatische Backups pausieren",
        @"resumeAutomaticBackups": @"Automatische Backups fortsetzen",
        @"automaticRetryRunning": @"Automatischer Wiederholungsversuch läuft",
        @"automaticRetryRunningShort": @"Retry läuft",
        @"backupProgressCurrentPhase": @"Fortschritt des aktuellen Bereichs",
        @"progressAreaFormat": @"Bereich %1$@ von %2$@",
        @"progressPreparing": @"Wird vorbereitet …",
        @"progressChecking": @"Änderungen werden gesucht …",
        @"progressTransferredFormat": @"%1$@ übertragen · %2$@",
        @"progressCheckedListedFormat": @"%1$@ geprüft · %2$@ erfasst",
        @"profileLabel": @"Profil",
        @"profileDefault": @"Standard",
        @"profileCreate": @"Neues Profil",
        @"profileRename": @"Profil umbenennen",
        @"profileDelete": @"Profil löschen",
        @"profileUnsavedSwitch": @"Ungespeicherte Änderungen müssen vor dem Profilwechsel verworfen werden.",
        @"profileActivated": @"Profil aktiviert.",
        @"profileNamePrompt": @"Namen für das Profil eingeben.",
        @"profileDeleteConfirm": @"Aktuelles Profil wirklich löschen?",
        @"discardChanges": @"Änderungen verwerfen",
        @"updateCheck": @"Nach Updates suchen …",
        @"updateChecking": @"Update wird gesucht …",
        @"updateAvailableTitle": @"Update verfügbar",
        @"updateAvailableMessage": @"Version %@ ist verfügbar. Die App lädt oder installiert nichts automatisch.",
        @"updateCurrentTitle": @"Du bist auf dem neuesten Stand",
        @"updateCurrentMessage": @"Version %@ ist bereits die neueste veröffentlichte Version.",
        @"updateUnavailableTitle": @"Updateprüfung nicht möglich",
        @"updateUnavailableMessage": @"Die GitHub-Veröffentlichungen konnten gerade nicht sicher geprüft werden. Es wurde nichts heruntergeladen.",
        @"updateOpenRelease": @"GitHub-Release öffnen",
        @"diagnosticsTitle": @"Diagnose",
        @"diagnosticsSubtitle": @"Systemzustand prüfen und sicheren Support-Bericht erstellen",
        @"diagnosticsOverallReady": @"Alles bereit.",
        @"diagnosticsOverallAttention": @"Einige Punkte brauchen Aufmerksamkeit.",
        @"diagnosticsTools": @"Werkzeuge",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"Backup-Ziel",
        @"diagnosticsSchedule": @"Zeitplan",
        @"diagnosticsLastRun": @"Letzter Lauf",
        @"diagnosticsController": @"Menüleistenservice",
        @"diagnosticsScript": @"Backup-Engine",
        @"diagnosticsReady": @"Bereit.",
        @"diagnosticsFailure": @"Prüfung fehlgeschlagen.",
        @"diagnosticsBlocked": @"Zuerst Werkzeuge installieren.",
        @"diagnosticsUnknown": @"Nicht geprüft.",
        @"diagnosticsMissingTools": @"Fehlt: %@",
        @"diagnosticsRefresh": @"Aktualisieren",
        @"diagnosticsRefreshing": @"Diagnose wird aktualisiert …",
        @"diagnosticsCopy": @"Sicheren Bericht kopieren",
        @"diagnosticsSave": @"Sicheren Bericht speichern …",
        @"diagnosticsPrivacy": @"Enthält keine Pfade, Zugangsdaten, Dateinamen oder Log-Inhalte.",
        @"diagnosticsCopied": @"Sicherer Bericht kopiert.",
        @"diagnosticsSaved": @"Sicherer Bericht gespeichert.",
        @"diagnosticsManual": @"Nur manuell",
        @"diagnosticsLoaded": @"Aktiv",
        @"diagnosticsNotLoaded": @"Nicht aktiv"
    };
    NSDictionary<NSString *, NSString *> *en = @{
        @"confirmTarget": @"Use this volume?",
        @"startBackup": @"Start backup",
        @"notNow": @"Not now",
        @"running": @"Backup is running ...",
        @"completed": @"Backup completed.",
        @"runningHint": @"Please do not eject the disk.",
        @"completedHint": @"Backup is done.",
        @"backupProgress": @"Backup progress",
        @"cancelBackup": @"Cancel backup …",
        @"cancelBackupConfirm": @"Cancel this backup?",
        @"cancelBackupDetail": @"The active copy will stop. Existing backups will be preserved.",
        @"cancelBackupAction": @"Cancel backup",
        @"cancellingBackup": @"Cancelling backup …",
        @"failed": @"Backup failed.",
        @"failedHint": @"No complete backup was created. Check the log.",
        @"failedPermissionHint": @"Target is not writable. Check NAS permissions.",
        @"failedNASConnectionHint": @"The NAS connection was lost. Reconnect the NAS and run the backup again.",
        @"notifyBackupFailures": @"Notify me when automatic backups fail",
        @"notifyBackupSuccesses": @"Notify me about successful automatic backups",
        @"backupNotificationSuccessTitle": @"Backup completed successfully",
        @"backupNotificationSuccessBody": @"The automatic backup completed successfully.",
        @"backupNotificationRecoverySuccessBody": @"A later automatic backup completed successfully. Your backup is current again.",
        @"backupNotificationRetrySuccessBody": @"The automatic retry completed successfully. Your backup is current again.",
        @"backupNotificationFailureTitle": @"Automatic backup failed",
        @"backupNotificationMissedTitle": @"Daily backup is missing",
        @"backupNotificationMissedBody": @"The backup scheduled for 20:00 was not completed successfully by 21:00.",
        @"backupNotificationTargetUnavailable": @"The backup destination is unavailable. Connect it and run the backup again.",
        @"backupNotificationNASRetryBody": @"The NAS is not fully ready yet. Another attempt will start automatically in 30 minutes.",
        @"backupNotificationRetryRunningTitle": @"Automatic backup retry is running",
        @"backupNotificationRetryRunningBody": @"GDrive is being backed up again. Open GDrive Backup Tiger to view progress.",
        @"backupNotificationRetryFailureBody": @"The automatic retry also failed. Check the NAS connection and run the backup again.",
        @"unknownExternalVolumeTitle": @"New external disk detected",
        @"unknownExternalVolumeBody": @"“%@” is not being used. No backup was started.",
        @"unknownExternalVolumeSetupAction": @"Set up as backup destination",
        @"unknownExternalVolumeIgnoreAction": @"Ignore",
        @"unknownExternalVolumeReviewSetup": @"“%@” is only staged. Save registers it for external-disk backups; the currently selected primary destination stays unchanged.",
        @"unknownExternalVolumeUnavailable": @"The disk is no longer available. Nothing was changed.",
        @"unknownExternalVolumeUnsupported": @"A writable APFS volume is required as a backup destination. Nothing was changed.",
        @"unknownExternalVolumeChooseTitle": @"Choose a backup volume",
        @"unknownExternalVolumeChooseBody": @"This disk contains several suitable APFS volumes. Explicitly choose the volume to stage.",
        @"unknownExternalVolumeChooseAction": @"Choose volume",
        @"unknownExternalVolumeChoosePlaceholder": @"Select a volume …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — mounted as “%2$@”",
        @"restoreTitle": @"Restore files",
        @"restoreSubtitle": @"Current and actually available older copies",
        @"restoreFilesColumn": @"Files and folders",
        @"restoreVersionsColumn": @"Available version",
        @"restoreSizeColumn": @"Size",
        @"restoreBack": @"Back",
        @"restoreOpenFolder": @"Open folder",
        @"restoreAction": @"Restore …",
        @"restoreLoading": @"Reading backup …",
        @"restoreEmpty": @"No restorable files were found in this folder.",
        @"restoreTargetUnavailable": @"The backup destination is unavailable. Connect it and try again.",
        @"restoreCurrent": @"Current backup",
        @"restoreHistorical": @"Older copy",
        @"restoreVerified": @"Restored and verified with SHA-256.",
        @"restoreIntegrityFailed": @"The restored file could not be verified safely.",
        @"restoreFailed": @"The file could not be restored. Check the destination and backup.",
        @"restoreShowInFinder": @"Show in Finder",
        @"restoreNoVersions": @"No safe copy is available for this file.",
        @"restoreChooseDestination": @"Choose a folder for the restored file.",
        @"cancelled": @"Backup cancelled.",
        @"cancelledHint": @"A successful completion was not confirmed.",
        @"skipped": @"No new backup started.",
        @"skippedHint": @"A backup is already running.",
        @"setupTitle": @"Backup target and trigger",
        @"targetType": @"App/schedule target",
        @"destinationPreview": @"Exact destination",
        @"externalVolume": @"External disk",
        @"encryptionLabel": @"Encryption",
        @"encryptionNone": @"None",
        @"encryptionAPFS": @"Encrypted APFS",
        @"encryptionAPFSTip": @"The app does not read or store a password.",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"rclone manages the key; the app does not read or store a password.",
        @"cryptRemoteLabel": @"Crypt remote",
        @"nas": @"NAS / Network",
        @"mountedNas": @"Mounted NAS",
        @"refresh": @"Refresh",
        @"discover": @"Search",
        @"openFinder": @"Open in Finder",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"Mount point",
        @"nasSubdir": @"Destination folder",
        @"schedule": @"Start",
        @"scheduleManual": @"Manual only",
        @"scheduleLogin": @"At login",
        @"scheduleHourly": @"Hourly",
        @"scheduleDaily": @"Daily 20:00",
        @"save": @"Save",
        @"dryRun": @"Check backup",
        @"dryRunRunning": @"Checking …",
        @"backupNow": @"Back up now",
        @"dryRunTip": @"Checks source and destination without copying files.",
        @"backupNowTip": @"Starts the real backup and writes to the selected destination.",
        @"statusReady": @"Ready.",
        @"statusSaved": @"Saved.",
        @"statusSearching": @"Searching network ...",
        @"statusDiscoveryDone": @"Network search completed.",
        @"statusBackupStarted": @"Backup started.",
        @"statusBackupPreparing": @"Preparing backup …",
        @"statusDryRunStarted": @"Checking backup … No files will be copied.",
        @"statusDryRunSucceeded": @"Check complete. Google Drive and the backup destination are reachable.",
        @"statusDryRunTargetUnavailable": @"Check failed: The backup destination is not connected.",
        @"statusDryRunFailed": @"Check failed. Open Diagnostics for details.",
        @"statusUnsavedChanges": @"Save changes first. No backup was started.",
        @"statusEncryptionIncompatible": @"This encryption mode is incompatible with the selected target.",
        @"statusCryptRemoteInvalid": @"Enter a safe crypt remote name different from the Google Drive remote.",
        @"setupCheckSectionTitle": @"System check",
        @"setupCheckButton": @"Check setup",
        @"setupCheckRunning": @"Checking …",
        @"setupCheckNotRun": @"Not checked yet.",
        @"setupCheckDependenciesLabel": @"Tools",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"Backup target",
        @"setupCheckDependenciesReady": @"All required tools are installed.",
        @"setupCheckDependenciesMissing": @"Missing: %@.",
        @"setupCheckRemoteBlocked": @"Install the missing tools first.",
        @"setupCheckRemoteMissing": @"The rclone remote is not configured.",
        @"setupCheckRemoteReady": @"Google Drive is reachable.",
        @"setupCheckRemoteUnavailable": @"Google Drive is currently unreachable.",
        @"setupCheckDestinationReady": @"The target is mounted and accessible.",
        @"setupCheckDestinationUnavailable": @"The target is unavailable or not writable.",
        @"setupCheckEncryptedAPFSRequired": @"An encrypted, unlocked APFS target is required.",
        @"setupCheckEncryptedAPFSReady": @"The encrypted APFS target is verified.",
        @"setupCheckRcloneCryptReady": @"rclone crypt fully protects this target.",
        @"setupCheckRcloneCryptInvalid": @"Check the crypt remote and its encryption options.",
        @"setupCheckReady": @"Setup is ready.",
        @"setupCheckNeedsAttention": @"Setup needs attention.",
        @"selectMountedVolume": @"Select volume",
        @"aboutMenu": @"About GDrive Backup Tiger",
        @"settingsMenu": @"Settings ...",
        @"hideMenu": @"Hide GDrive Backup Tiger",
        @"quitMenu": @"Quit GDrive Backup Tiger",
        @"settingsTitle": @"Settings",
        @"languageSetting": @"Language",
        @"cancel": @"Cancel",
        @"done": @"Done",
        @"languageSaved": @"Language saved.",
        @"overviewSubtitle": @"Independent copy · clear status · ready to restore",
        @"overviewLastRun": @"Last backup",
        @"overviewNextRun": @"Next run",
        @"overviewTarget": @"Destination",
        @"overviewStorage": @"Destination free space",
        @"overviewSettings": @"Set up backup …",
        @"overviewOpen": @"Open GDrive Backup Tiger",
        @"overviewNeverRun": @"No backup yet",
        @"overviewUnavailable": @"Not available",
        @"overviewFreeOf": @"%@ free of %@",
        @"overviewStatusInterrupted": @"Backup was interrupted.",
        @"overviewStatusUnknown": @"Backup status unknown.",
        @"automaticBackupsPaused": @"Automatic backups paused",
        @"pauseAutomaticBackups": @"Pause automatic backups",
        @"resumeAutomaticBackups": @"Resume automatic backups",
        @"automaticRetryRunning": @"Automatic retry is running",
        @"automaticRetryRunningShort": @"Retry running",
        @"backupProgressCurrentPhase": @"Current area progress",
        @"progressAreaFormat": @"Area %1$@ of %2$@",
        @"progressPreparing": @"Preparing …",
        @"progressChecking": @"Checking for changes …",
        @"progressTransferredFormat": @"%1$@ transferred · %2$@",
        @"progressCheckedListedFormat": @"%1$@ checked · %2$@ listed",
        @"profileLabel": @"Profile",
        @"profileDefault": @"Default",
        @"profileCreate": @"New profile",
        @"profileRename": @"Rename profile",
        @"profileDelete": @"Delete profile",
        @"profileUnsavedSwitch": @"Unsaved changes must be discarded before switching profiles.",
        @"profileActivated": @"Profile activated.",
        @"profileNamePrompt": @"Enter a name for the profile.",
        @"profileDeleteConfirm": @"Delete the current profile?",
        @"discardChanges": @"Discard changes",
        @"updateCheck": @"Check for Updates …",
        @"updateChecking": @"Checking for update …",
        @"updateAvailableTitle": @"Update available",
        @"updateAvailableMessage": @"Version %@ is available. The app does not download or install anything automatically.",
        @"updateCurrentTitle": @"You’re up to date",
        @"updateCurrentMessage": @"Version %@ is already the latest published version.",
        @"updateUnavailableTitle": @"Could not check for updates",
        @"updateUnavailableMessage": @"GitHub releases could not be checked safely right now. Nothing was downloaded.",
        @"updateOpenRelease": @"Open GitHub release",
        @"diagnosticsTitle": @"Diagnostics",
        @"diagnosticsSubtitle": @"Check system health and create a safe support report",
        @"diagnosticsOverallReady": @"Everything is ready.",
        @"diagnosticsOverallAttention": @"Some items need attention.",
        @"diagnosticsTools": @"Tools",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"Backup destination",
        @"diagnosticsSchedule": @"Schedule",
        @"diagnosticsLastRun": @"Last run",
        @"diagnosticsController": @"Menu bar service",
        @"diagnosticsScript": @"Backup engine",
        @"diagnosticsReady": @"Ready.",
        @"diagnosticsFailure": @"Check failed.",
        @"diagnosticsBlocked": @"Install the tools first.",
        @"diagnosticsUnknown": @"Not checked.",
        @"diagnosticsMissingTools": @"Missing: %@",
        @"diagnosticsRefresh": @"Refresh",
        @"diagnosticsRefreshing": @"Refreshing diagnostics …",
        @"diagnosticsCopy": @"Copy safe report",
        @"diagnosticsSave": @"Save safe report …",
        @"diagnosticsPrivacy": @"Contains no paths, credentials, file names, or log contents.",
        @"diagnosticsCopied": @"Safe report copied.",
        @"diagnosticsSaved": @"Safe report saved.",
        @"diagnosticsManual": @"Manual only",
        @"diagnosticsLoaded": @"Active",
        @"diagnosticsNotLoaded": @"Not active"
    };
    NSDictionary<NSString *, NSString *> *fr = @{
        @"confirmTarget": @"Utiliser ce volume ?",
        @"startBackup": @"Sauvegarder",
        @"notNow": @"Pas maintenant",
        @"running": @"Sauvegarde en cours ...",
        @"completed": @"Sauvegarde terminée.",
        @"runningHint": @"Veuillez ne pas éjecter le disque.",
        @"completedHint": @"Sauvegarde terminée.",
        @"backupProgress": @"Progression de la sauvegarde",
        @"cancelBackup": @"Annuler la sauvegarde…",
        @"cancelBackupConfirm": @"Annuler cette sauvegarde ?",
        @"cancelBackupDetail": @"La copie en cours sera arrêtée. Les sauvegardes existantes seront conservées.",
        @"cancelBackupAction": @"Annuler la sauvegarde",
        @"cancellingBackup": @"Annulation de la sauvegarde…",
        @"failed": @"Échec de la sauvegarde.",
        @"failedHint": @"Aucune sauvegarde complète. Consultez le journal.",
        @"failedPermissionHint": @"Cible non accessible en écriture. Vérifiez les droits NAS.",
        @"failedNASConnectionHint": @"La connexion au NAS a été interrompue. Reconnectez-le et relancez la sauvegarde.",
        @"notifyBackupFailures": @"M’avertir en cas d’échec d’une sauvegarde automatique",
        @"notifyBackupSuccesses": @"M’avertir aussi quand les sauvegardes automatiques réussissent",
        @"backupNotificationSuccessTitle": @"Sauvegarde terminée avec succès",
        @"backupNotificationSuccessBody": @"La sauvegarde automatique s’est terminée avec succès.",
        @"backupNotificationRecoverySuccessBody": @"Une sauvegarde automatique ultérieure s’est terminée avec succès. Votre sauvegarde est de nouveau à jour.",
        @"backupNotificationRetrySuccessBody": @"La nouvelle tentative automatique a réussi. Votre sauvegarde est de nouveau à jour.",
        @"backupNotificationFailureTitle": @"Échec de la sauvegarde automatique",
        @"backupNotificationMissedTitle": @"La sauvegarde quotidienne est absente",
        @"backupNotificationMissedBody": @"La sauvegarde prévue à 20:00 ne s’est pas terminée correctement avant 21:00.",
        @"backupNotificationTargetUnavailable": @"La destination de sauvegarde est indisponible. Reconnectez-la et relancez la sauvegarde.",
        @"backupNotificationNASRetryBody": @"Le NAS n’est pas encore entièrement prêt. Une nouvelle tentative démarrera automatiquement dans 30 minutes.",
        @"backupNotificationRetryRunningTitle": @"Nouvelle tentative de sauvegarde automatique en cours",
        @"backupNotificationRetryRunningBody": @"Une nouvelle sauvegarde de GDrive est en cours. Ouvrez GDrive Backup Tiger pour suivre la progression.",
        @"backupNotificationRetryFailureBody": @"La nouvelle tentative automatique a également échoué. Vérifiez la connexion NAS et relancez la sauvegarde.",
        @"unknownExternalVolumeTitle": @"Nouveau disque externe détecté",
        @"unknownExternalVolumeBody": @"« %@ » n’est pas utilisé. Aucune sauvegarde n’a démarré.",
        @"unknownExternalVolumeSetupAction": @"Configurer comme destination",
        @"unknownExternalVolumeIgnoreAction": @"Ignorer",
        @"unknownExternalVolumeReviewSetup": @"« %@ » est seulement présélectionné. Enregistrer l’inscrit pour les sauvegardes sur disque externe ; la destination principale sélectionnée reste inchangée.",
        @"unknownExternalVolumeUnavailable": @"Le disque n’est plus disponible. Rien n’a été modifié.",
        @"unknownExternalVolumeUnsupported": @"Un volume APFS inscriptible est requis comme destination. Rien n’a été modifié.",
        @"unknownExternalVolumeChooseTitle": @"Choisir un volume de sauvegarde",
        @"unknownExternalVolumeChooseBody": @"Ce disque contient plusieurs volumes APFS appropriés. Choisissez explicitement le volume à présélectionner.",
        @"unknownExternalVolumeChooseAction": @"Choisir le volume",
        @"unknownExternalVolumeChoosePlaceholder": @"Sélectionnez un volume …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — monté sous « %2$@ »",
        @"restoreTitle": @"Restaurer des fichiers",
        @"restoreSubtitle": @"Copies actuelles et anciennes réellement disponibles",
        @"restoreFilesColumn": @"Fichiers et dossiers",
        @"restoreVersionsColumn": @"Version disponible",
        @"restoreSizeColumn": @"Taille",
        @"restoreBack": @"Retour",
        @"restoreOpenFolder": @"Ouvrir le dossier",
        @"restoreAction": @"Restaurer…",
        @"restoreLoading": @"Lecture de la sauvegarde…",
        @"restoreEmpty": @"Aucun fichier restaurable n’a été trouvé dans ce dossier.",
        @"restoreTargetUnavailable": @"La destination de sauvegarde est indisponible. Reconnectez-la et réessayez.",
        @"restoreCurrent": @"Sauvegarde actuelle",
        @"restoreHistorical": @"Copie antérieure",
        @"restoreVerified": @"Fichier restauré et vérifié avec SHA-256.",
        @"restoreIntegrityFailed": @"Le fichier restauré n’a pas pu être vérifié en toute sécurité.",
        @"restoreFailed": @"Le fichier n’a pas pu être restauré. Vérifiez la destination et la sauvegarde.",
        @"restoreShowInFinder": @"Afficher dans le Finder",
        @"restoreNoVersions": @"Aucune copie sûre n’est disponible pour ce fichier.",
        @"restoreChooseDestination": @"Choisissez un dossier pour le fichier restauré.",
        @"cancelled": @"Sauvegarde annulée.",
        @"cancelledHint": @"Aucune fin réussie n’a été confirmée.",
        @"skipped": @"Aucune nouvelle sauvegarde lancée.",
        @"skippedHint": @"Une sauvegarde est déjà en cours.",
        @"setupTitle": @"Destination et mode de démarrage",
        @"targetType": @"Destination app/planifiée",
        @"destinationPreview": @"Destination exacte",
        @"externalVolume": @"Disque externe",
        @"encryptionLabel": @"Chiffrement",
        @"encryptionNone": @"Aucun",
        @"encryptionAPFS": @"APFS chiffré",
        @"encryptionAPFSTip": @"L’app ne lit ni n’enregistre aucun mot de passe.",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"rclone gère la clé ; l’app ne lit ni n’enregistre aucun mot de passe.",
        @"cryptRemoteLabel": @"Remote crypt",
        @"nas": @"NAS / Réseau",
        @"mountedNas": @"NAS monté",
        @"refresh": @"Actualiser",
        @"discover": @"Rechercher",
        @"openFinder": @"Ouvrir dans le Finder",
        @"nasUrl": @"URL du NAS",
        @"nasMount": @"Point de montage",
        @"nasSubdir": @"Dossier cible",
        @"schedule": @"Démarrage",
        @"scheduleManual": @"Manuel uniquement",
        @"scheduleLogin": @"À la connexion",
        @"scheduleHourly": @"Toutes les heures",
        @"scheduleDaily": @"Tous les jours 20:00",
        @"save": @"Enregistrer",
        @"dryRun": @"Vérifier la sauvegarde",
        @"dryRunRunning": @"Vérification…",
        @"backupNow": @"Sauvegarder",
        @"dryRunTip": @"Vérifie la source et la destination sans copier de fichiers.",
        @"backupNowTip": @"Lance la vraie sauvegarde vers la destination choisie.",
        @"statusReady": @"Prêt.",
        @"statusSaved": @"Enregistré.",
        @"statusSearching": @"Recherche sur le réseau ...",
        @"statusDiscoveryDone": @"Recherche réseau terminée.",
        @"statusBackupStarted": @"Sauvegarde lancée.",
        @"statusBackupPreparing": @"Préparation de la sauvegarde…",
        @"statusDryRunStarted": @"Vérification de la sauvegarde… Aucun fichier ne sera copié.",
        @"statusDryRunSucceeded": @"Vérification terminée. Google Drive et la destination sont accessibles.",
        @"statusDryRunTargetUnavailable": @"Échec de la vérification : la destination n’est pas connectée.",
        @"statusDryRunFailed": @"Échec de la vérification. Consultez le diagnostic pour plus de détails.",
        @"statusUnsavedChanges": @"Enregistrez d’abord les modifications. Aucune sauvegarde lancée.",
        @"statusEncryptionIncompatible": @"Ce chiffrement est incompatible avec la destination choisie.",
        @"statusCryptRemoteInvalid": @"Saisissez un remote crypt sûr, différent du remote Google Drive.",
        @"setupCheckSectionTitle": @"Vérification du système",
        @"setupCheckButton": @"Vérifier la configuration",
        @"setupCheckRunning": @"Vérification en cours…",
        @"setupCheckNotRun": @"Pas encore vérifié.",
        @"setupCheckDependenciesLabel": @"Outils",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"Destination",
        @"setupCheckDependenciesReady": @"Tous les outils requis sont installés.",
        @"setupCheckDependenciesMissing": @"Manquant : %@.",
        @"setupCheckRemoteBlocked": @"Installez d’abord les outils manquants.",
        @"setupCheckRemoteMissing": @"Le remote rclone n’est pas configuré.",
        @"setupCheckRemoteReady": @"Google Drive est accessible.",
        @"setupCheckRemoteUnavailable": @"Google Drive est momentanément inaccessible.",
        @"setupCheckDestinationReady": @"La destination est montée et accessible.",
        @"setupCheckDestinationUnavailable": @"La destination est indisponible ou non inscriptible.",
        @"setupCheckEncryptedAPFSRequired": @"Une destination APFS chiffrée et déverrouillée est requise.",
        @"setupCheckEncryptedAPFSReady": @"La destination APFS chiffrée est vérifiée.",
        @"setupCheckRcloneCryptReady": @"rclone crypt protège entièrement cette destination.",
        @"setupCheckRcloneCryptInvalid": @"Vérifiez le remote crypt et ses options de chiffrement.",
        @"setupCheckReady": @"La configuration est prête.",
        @"setupCheckNeedsAttention": @"La configuration nécessite votre attention.",
        @"selectMountedVolume": @"Choisir un volume",
        @"aboutMenu": @"À propos de GDrive Backup Tiger",
        @"settingsMenu": @"Réglages ...",
        @"hideMenu": @"Masquer GDrive Backup Tiger",
        @"quitMenu": @"Quitter GDrive Backup Tiger",
        @"settingsTitle": @"Réglages",
        @"languageSetting": @"Langue",
        @"cancel": @"Annuler",
        @"done": @"Terminé",
        @"languageSaved": @"Langue enregistrée.",
        @"overviewSubtitle": @"Copie indépendante · état clair · restauration prête",
        @"overviewLastRun": @"Dernière sauvegarde",
        @"overviewNextRun": @"Prochaine exécution",
        @"overviewTarget": @"Destination",
        @"overviewStorage": @"Espace libre à destination",
        @"overviewSettings": @"Configurer la sauvegarde …",
        @"overviewOpen": @"Ouvrir GDrive Backup Tiger",
        @"overviewNeverRun": @"Aucune sauvegarde",
        @"overviewUnavailable": @"Indisponible",
        @"overviewFreeOf": @"%@ libres sur %@",
        @"overviewStatusInterrupted": @"La sauvegarde a été interrompue.",
        @"overviewStatusUnknown": @"État de sauvegarde inconnu.",
        @"automaticBackupsPaused": @"Sauvegardes automatiques en pause",
        @"pauseAutomaticBackups": @"Suspendre les sauvegardes automatiques",
        @"resumeAutomaticBackups": @"Reprendre les sauvegardes automatiques",
        @"automaticRetryRunning": @"Nouvelle tentative automatique en cours",
        @"automaticRetryRunningShort": @"Nouvelle tentative en cours",
        @"backupProgressCurrentPhase": @"Progression de la zone actuelle",
        @"progressAreaFormat": @"Zone %1$@ sur %2$@",
        @"progressPreparing": @"Préparation…",
        @"progressChecking": @"Recherche des modifications…",
        @"progressTransferredFormat": @"%1$@ transférés · %2$@",
        @"progressCheckedListedFormat": @"%1$@ vérifiés · %2$@ répertoriés",
        @"profileLabel": @"Profil",
        @"profileDefault": @"Par défaut",
        @"profileCreate": @"Nouveau profil",
        @"profileRename": @"Renommer le profil",
        @"profileDelete": @"Supprimer le profil",
        @"profileUnsavedSwitch": @"Les modifications non enregistrées doivent être ignorées avant de changer de profil.",
        @"profileActivated": @"Profil activé.",
        @"profileNamePrompt": @"Saisissez un nom pour le profil.",
        @"profileDeleteConfirm": @"Supprimer le profil actuel ?",
        @"discardChanges": @"Ignorer les modifications",
        @"updateCheck": @"Rechercher les mises à jour…",
        @"updateChecking": @"Recherche d’une mise à jour…",
        @"updateAvailableTitle": @"Mise à jour disponible",
        @"updateAvailableMessage": @"La version %@ est disponible. L’app ne télécharge et n’installe rien automatiquement.",
        @"updateCurrentTitle": @"L’app est à jour",
        @"updateCurrentMessage": @"La version %@ est déjà la dernière version publiée.",
        @"updateUnavailableTitle": @"Recherche impossible",
        @"updateUnavailableMessage": @"Les versions GitHub n’ont pas pu être vérifiées de manière sûre. Aucun téléchargement n’a été effectué.",
        @"updateOpenRelease": @"Ouvrir la version GitHub",
        @"diagnosticsTitle": @"Diagnostic",
        @"diagnosticsSubtitle": @"Vérifier le système et créer un rapport d’assistance sûr",
        @"diagnosticsOverallReady": @"Tout est prêt.",
        @"diagnosticsOverallAttention": @"Certains éléments nécessitent votre attention.",
        @"diagnosticsTools": @"Outils",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"Destination de sauvegarde",
        @"diagnosticsSchedule": @"Planification",
        @"diagnosticsLastRun": @"Dernière exécution",
        @"diagnosticsController": @"Service de barre des menus",
        @"diagnosticsScript": @"Moteur de sauvegarde",
        @"diagnosticsReady": @"Prêt.",
        @"diagnosticsFailure": @"Échec de la vérification.",
        @"diagnosticsBlocked": @"Installez d’abord les outils.",
        @"diagnosticsUnknown": @"Non vérifié.",
        @"diagnosticsMissingTools": @"Manquant : %@",
        @"diagnosticsRefresh": @"Actualiser",
        @"diagnosticsRefreshing": @"Actualisation du diagnostic…",
        @"diagnosticsCopy": @"Copier le rapport sûr",
        @"diagnosticsSave": @"Enregistrer le rapport sûr…",
        @"diagnosticsPrivacy": @"Ne contient aucun chemin, identifiant, nom de fichier ni contenu de journal.",
        @"diagnosticsCopied": @"Rapport sûr copié.",
        @"diagnosticsSaved": @"Rapport sûr enregistré.",
        @"diagnosticsManual": @"Manuel uniquement",
        @"diagnosticsLoaded": @"Actif",
        @"diagnosticsNotLoaded": @"Inactif"
    };
    NSDictionary<NSString *, NSString *> *es = @{
        @"confirmTarget": @"¿Usar este volumen?",
        @"startBackup": @"Iniciar copia",
        @"notNow": @"Ahora no",
        @"running": @"Copia en curso ...",
        @"completed": @"Copia completada.",
        @"runningHint": @"No expulses el disco.",
        @"completedHint": @"La copia esta lista.",
        @"backupProgress": @"Progreso de la copia",
        @"cancelBackup": @"Cancelar copia de seguridad…",
        @"cancelBackupConfirm": @"¿Cancelar esta copia de seguridad?",
        @"cancelBackupDetail": @"La copia en curso se detendrá. Las copias existentes se conservarán.",
        @"cancelBackupAction": @"Cancelar copia",
        @"cancellingBackup": @"Cancelando la copia…",
        @"failed": @"La copia ha fallado.",
        @"failedHint": @"No se creó una copia completa. Revisa el registro.",
        @"failedPermissionHint": @"No se puede escribir en el destino. Revisa los permisos del NAS.",
        @"failedNASConnectionHint": @"Se perdió la conexión con el NAS. Vuelve a conectarlo y repite la copia.",
        @"notifyBackupFailures": @"Avisarme si falla una copia automática",
        @"notifyBackupSuccesses": @"Avísame también de las copias automáticas correctas",
        @"backupNotificationSuccessTitle": @"Copia de seguridad terminada correctamente",
        @"backupNotificationSuccessBody": @"La copia automática terminó correctamente.",
        @"backupNotificationRecoverySuccessBody": @"Una copia automática posterior terminó correctamente. Tu copia vuelve a estar al día.",
        @"backupNotificationRetrySuccessBody": @"El reintento automático terminó correctamente. Tu copia vuelve a estar al día.",
        @"backupNotificationFailureTitle": @"Falló la copia automática",
        @"backupNotificationMissedTitle": @"Falta la copia diaria",
        @"backupNotificationMissedBody": @"La copia programada para las 20:00 no terminó correctamente antes de las 21:00.",
        @"backupNotificationTargetUnavailable": @"El destino de la copia no está disponible. Conéctalo y vuelve a ejecutar la copia.",
        @"backupNotificationNASRetryBody": @"El NAS aún no está completamente listo. Se iniciará otro intento automáticamente en 30 minutos.",
        @"backupNotificationRetryRunningTitle": @"Reintento automático de copia de seguridad en curso",
        @"backupNotificationRetryRunningBody": @"Se está realizando de nuevo la copia de seguridad de GDrive. Abre GDrive Backup Tiger para ver el progreso.",
        @"backupNotificationRetryFailureBody": @"El reintento automático también falló. Revisa la conexión del NAS y vuelve a ejecutar la copia.",
        @"unknownExternalVolumeTitle": @"Nuevo disco externo detectado",
        @"unknownExternalVolumeBody": @"«%@» no se está usando. No se inició ninguna copia.",
        @"unknownExternalVolumeSetupAction": @"Configurar como destino",
        @"unknownExternalVolumeIgnoreAction": @"Ignorar",
        @"unknownExternalVolumeReviewSetup": @"«%@» solo está preseleccionado. Guardar lo registra para copias en disco externo; el destino principal seleccionado no cambia.",
        @"unknownExternalVolumeUnavailable": @"El disco ya no está disponible. No se cambió nada.",
        @"unknownExternalVolumeUnsupported": @"Se necesita un volumen APFS con escritura como destino. No se cambió nada.",
        @"unknownExternalVolumeChooseTitle": @"Elegir volumen de copia",
        @"unknownExternalVolumeChooseBody": @"Este disco contiene varios volúmenes APFS adecuados. Elige expresamente el volumen que quieres preseleccionar.",
        @"unknownExternalVolumeChooseAction": @"Elegir volumen",
        @"unknownExternalVolumeChoosePlaceholder": @"Selecciona un volumen …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — montado como «%2$@»",
        @"restoreTitle": @"Restaurar archivos",
        @"restoreSubtitle": @"Copias actuales y anteriores realmente disponibles",
        @"restoreFilesColumn": @"Archivos y carpetas",
        @"restoreVersionsColumn": @"Versión disponible",
        @"restoreSizeColumn": @"Tamaño",
        @"restoreBack": @"Atrás",
        @"restoreOpenFolder": @"Abrir carpeta",
        @"restoreAction": @"Restaurar…",
        @"restoreLoading": @"Leyendo la copia…",
        @"restoreEmpty": @"No se encontraron archivos restaurables en esta carpeta.",
        @"restoreTargetUnavailable": @"El destino de la copia no está disponible. Conéctalo e inténtalo de nuevo.",
        @"restoreCurrent": @"Copia actual",
        @"restoreHistorical": @"Copia anterior",
        @"restoreVerified": @"Archivo restaurado y verificado con SHA-256.",
        @"restoreIntegrityFailed": @"No se pudo verificar de forma segura el archivo restaurado.",
        @"restoreFailed": @"No se pudo restaurar el archivo. Revisa el destino y la copia.",
        @"restoreShowInFinder": @"Mostrar en Finder",
        @"restoreNoVersions": @"No hay una copia segura disponible para este archivo.",
        @"restoreChooseDestination": @"Elige una carpeta para el archivo restaurado.",
        @"cancelled": @"Copia cancelada.",
        @"cancelledHint": @"No se confirmó una finalización correcta.",
        @"skipped": @"No se inició una copia nueva.",
        @"skippedHint": @"Ya hay una copia en curso.",
        @"setupTitle": @"Destino y modo de inicio",
        @"targetType": @"Destino app/programado",
        @"destinationPreview": @"Destino exacto",
        @"externalVolume": @"Disco externo",
        @"encryptionLabel": @"Cifrado",
        @"encryptionNone": @"Ninguno",
        @"encryptionAPFS": @"APFS cifrado",
        @"encryptionAPFSTip": @"La app no lee ni guarda ninguna contraseña.",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"rclone gestiona la clave; la app no lee ni guarda contraseñas.",
        @"cryptRemoteLabel": @"Remoto crypt",
        @"nas": @"NAS / Red",
        @"mountedNas": @"NAS montado",
        @"refresh": @"Actualizar",
        @"discover": @"Buscar",
        @"openFinder": @"Abrir en Finder",
        @"nasUrl": @"URL del NAS",
        @"nasMount": @"Punto de montaje",
        @"nasSubdir": @"Carpeta destino",
        @"schedule": @"Inicio",
        @"scheduleManual": @"Solo manual",
        @"scheduleLogin": @"Al iniciar sesión",
        @"scheduleHourly": @"Cada hora",
        @"scheduleDaily": @"Diario 20:00",
        @"save": @"Guardar",
        @"dryRun": @"Comprobar copia",
        @"dryRunRunning": @"Comprobando…",
        @"backupNow": @"Copiar ahora",
        @"dryRunTip": @"Comprueba origen y destino sin copiar archivos.",
        @"backupNowTip": @"Inicia la copia real hacia el destino elegido.",
        @"statusReady": @"Listo.",
        @"statusSaved": @"Guardado.",
        @"statusSearching": @"Buscando en la red ...",
        @"statusDiscoveryDone": @"Búsqueda de red completada.",
        @"statusBackupStarted": @"Copia iniciada.",
        @"statusBackupPreparing": @"Preparando la copia…",
        @"statusDryRunStarted": @"Comprobando la copia… No se copiarán archivos.",
        @"statusDryRunSucceeded": @"Comprobación completada. Google Drive y el destino están disponibles.",
        @"statusDryRunTargetUnavailable": @"Error de comprobación: el destino no está conectado.",
        @"statusDryRunFailed": @"Error de comprobación. Consulta Diagnóstico para más detalles.",
        @"statusUnsavedChanges": @"Guarda primero los cambios. No se inició ninguna copia.",
        @"statusEncryptionIncompatible": @"Este cifrado no es compatible con el destino seleccionado.",
        @"statusCryptRemoteInvalid": @"Introduce un remoto crypt seguro y distinto del remoto de Google Drive.",
        @"setupCheckSectionTitle": @"Comprobación del sistema",
        @"setupCheckButton": @"Comprobar configuración",
        @"setupCheckRunning": @"Comprobando…",
        @"setupCheckNotRun": @"Aún no comprobado.",
        @"setupCheckDependenciesLabel": @"Herramientas",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"Destino",
        @"setupCheckDependenciesReady": @"Todas las herramientas necesarias están instaladas.",
        @"setupCheckDependenciesMissing": @"Falta: %@.",
        @"setupCheckRemoteBlocked": @"Instala primero las herramientas que faltan.",
        @"setupCheckRemoteMissing": @"El remote de rclone no está configurado.",
        @"setupCheckRemoteReady": @"Google Drive está accesible.",
        @"setupCheckRemoteUnavailable": @"Google Drive no está accesible ahora.",
        @"setupCheckDestinationReady": @"El destino está montado y accesible.",
        @"setupCheckDestinationUnavailable": @"El destino no está disponible o no permite escritura.",
        @"setupCheckEncryptedAPFSRequired": @"Se requiere un destino APFS cifrado y desbloqueado.",
        @"setupCheckEncryptedAPFSReady": @"El destino APFS cifrado está verificado.",
        @"setupCheckRcloneCryptReady": @"rclone crypt protege completamente este destino.",
        @"setupCheckRcloneCryptInvalid": @"Revisa el remoto crypt y sus opciones de cifrado.",
        @"setupCheckReady": @"La configuración está lista.",
        @"setupCheckNeedsAttention": @"La configuración necesita atención.",
        @"selectMountedVolume": @"Seleccionar volumen",
        @"aboutMenu": @"Acerca de GDrive Backup Tiger",
        @"settingsMenu": @"Configuración ...",
        @"hideMenu": @"Ocultar GDrive Backup Tiger",
        @"quitMenu": @"Salir de GDrive Backup Tiger",
        @"settingsTitle": @"Configuración",
        @"languageSetting": @"Idioma",
        @"cancel": @"Cancelar",
        @"done": @"Listo",
        @"languageSaved": @"Idioma guardado.",
        @"overviewSubtitle": @"Copia independiente · estado claro · lista para restaurar",
        @"overviewLastRun": @"Última copia",
        @"overviewNextRun": @"Próxima ejecución",
        @"overviewTarget": @"Destino",
        @"overviewStorage": @"Espacio libre en destino",
        @"overviewSettings": @"Configurar copia …",
        @"overviewOpen": @"Abrir GDrive Backup Tiger",
        @"overviewNeverRun": @"Aún no hay copia",
        @"overviewUnavailable": @"No disponible",
        @"overviewFreeOf": @"%@ libres de %@",
        @"overviewStatusInterrupted": @"La copia fue interrumpida.",
        @"overviewStatusUnknown": @"Estado de copia desconocido.",
        @"automaticBackupsPaused": @"Copias automáticas en pausa",
        @"pauseAutomaticBackups": @"Pausar copias automáticas",
        @"resumeAutomaticBackups": @"Reanudar copias automáticas",
        @"automaticRetryRunning": @"Reintento automático en curso",
        @"automaticRetryRunningShort": @"Reintento en curso",
        @"backupProgressCurrentPhase": @"Progreso del área actual",
        @"progressAreaFormat": @"Área %1$@ de %2$@",
        @"progressPreparing": @"Preparando…",
        @"progressChecking": @"Buscando cambios…",
        @"progressTransferredFormat": @"%1$@ transferidos · %2$@",
        @"progressCheckedListedFormat": @"%1$@ comprobados · %2$@ listados",
        @"profileLabel": @"Perfil",
        @"profileDefault": @"Predeterminado",
        @"profileCreate": @"Nuevo perfil",
        @"profileRename": @"Renombrar perfil",
        @"profileDelete": @"Eliminar perfil",
        @"profileUnsavedSwitch": @"Debes descartar los cambios sin guardar antes de cambiar de perfil.",
        @"profileActivated": @"Perfil activado.",
        @"profileNamePrompt": @"Introduce un nombre para el perfil.",
        @"profileDeleteConfirm": @"¿Eliminar el perfil actual?",
        @"discardChanges": @"Descartar cambios",
        @"updateCheck": @"Buscar actualizaciones…",
        @"updateChecking": @"Buscando actualización…",
        @"updateAvailableTitle": @"Actualización disponible",
        @"updateAvailableMessage": @"La versión %@ está disponible. La app no descarga ni instala nada automáticamente.",
        @"updateCurrentTitle": @"La app está actualizada",
        @"updateCurrentMessage": @"La versión %@ ya es la última versión publicada.",
        @"updateUnavailableTitle": @"No se pudo buscar actualizaciones",
        @"updateUnavailableMessage": @"No se pudieron comprobar de forma segura las versiones de GitHub. No se descargó nada.",
        @"updateOpenRelease": @"Abrir versión en GitHub",
        @"diagnosticsTitle": @"Diagnóstico",
        @"diagnosticsSubtitle": @"Comprobar el sistema y crear un informe de soporte seguro",
        @"diagnosticsOverallReady": @"Todo está listo.",
        @"diagnosticsOverallAttention": @"Algunos elementos requieren atención.",
        @"diagnosticsTools": @"Herramientas",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"Destino de la copia",
        @"diagnosticsSchedule": @"Programación",
        @"diagnosticsLastRun": @"Última ejecución",
        @"diagnosticsController": @"Servicio de la barra de menús",
        @"diagnosticsScript": @"Motor de copias",
        @"diagnosticsReady": @"Listo.",
        @"diagnosticsFailure": @"La comprobación falló.",
        @"diagnosticsBlocked": @"Instala primero las herramientas.",
        @"diagnosticsUnknown": @"Sin comprobar.",
        @"diagnosticsMissingTools": @"Falta: %@",
        @"diagnosticsRefresh": @"Actualizar",
        @"diagnosticsRefreshing": @"Actualizando diagnóstico…",
        @"diagnosticsCopy": @"Copiar informe seguro",
        @"diagnosticsSave": @"Guardar informe seguro…",
        @"diagnosticsPrivacy": @"No contiene rutas, credenciales, nombres de archivo ni contenido de registros.",
        @"diagnosticsCopied": @"Informe seguro copiado.",
        @"diagnosticsSaved": @"Informe seguro guardado.",
        @"diagnosticsManual": @"Solo manual",
        @"diagnosticsLoaded": @"Activo",
        @"diagnosticsNotLoaded": @"Inactivo"
    };
    NSDictionary<NSString *, NSString *> *ja = @{
        @"confirmTarget": @"このボリュームを使いますか？",
        @"startBackup": @"バックアップ開始",
        @"notNow": @"今はしない",
        @"running": @"バックアップ中...",
        @"completed": @"バックアップ完了。",
        @"runningHint": @"ディスクを取り出さないでください。",
        @"completedHint": @"完了しました。",
        @"backupProgress": @"バックアップの進行状況",
        @"cancelBackup": @"バックアップを中止…",
        @"cancelBackupConfirm": @"このバックアップを中止しますか？",
        @"cancelBackupDetail": @"実行中のコピーを停止します。既存のバックアップは保持されます。",
        @"cancelBackupAction": @"バックアップを中止",
        @"cancellingBackup": @"バックアップを中止しています…",
        @"failed": @"バックアップに失敗しました。",
        @"failedHint": @"完全なバックアップは作成されていません。ログを確認してください。",
        @"failedPermissionHint": @"保存先に書き込めません。NASの権限を確認してください。",
        @"failedNASConnectionHint": @"NASへの接続が切れました。再接続してバックアップをやり直してください。",
        @"notifyBackupFailures": @"自動バックアップの失敗を通知",
        @"notifyBackupSuccesses": @"自動バックアップの成功も通知",
        @"backupNotificationSuccessTitle": @"バックアップが正常に完了しました",
        @"backupNotificationSuccessBody": @"自動バックアップが正常に完了しました。",
        @"backupNotificationRecoverySuccessBody": @"その後の自動バックアップが正常に完了しました。バックアップは再び最新です。",
        @"backupNotificationRetrySuccessBody": @"自動再試行が正常に完了しました。バックアップは再び最新です。",
        @"backupNotificationFailureTitle": @"自動バックアップに失敗しました",
        @"backupNotificationMissedTitle": @"日次バックアップがありません",
        @"backupNotificationMissedBody": @"20:00に予定されたバックアップは21:00までに正常完了しませんでした。",
        @"backupNotificationTargetUnavailable": @"バックアップ先を利用できません。接続してバックアップを再実行してください。",
        @"backupNotificationNASRetryBody": @"NASの準備がまだ完了していません。30分後に自動で再試行します。",
        @"backupNotificationRetryRunningTitle": @"自動バックアップを再試行中",
        @"backupNotificationRetryRunningBody": @"GDrive をもう一度バックアップしています。進行状況を確認するには GDrive Backup Tiger を開いてください。",
        @"backupNotificationRetryFailureBody": @"自動再試行にも失敗しました。NAS接続を確認してバックアップを再実行してください。",
        @"unknownExternalVolumeTitle": @"新しい外付けディスクを検出しました",
        @"unknownExternalVolumeBody": @"「%@」は使用されていません。バックアップは開始されませんでした。",
        @"unknownExternalVolumeSetupAction": @"バックアップ先として設定",
        @"unknownExternalVolumeIgnoreAction": @"無視",
        @"unknownExternalVolumeReviewSetup": @"「%@」は仮登録です。「保存」で外付けディスク用のバックアップ先として登録されますが、現在選択中の主な保存先は変わりません。",
        @"unknownExternalVolumeUnavailable": @"ディスクは利用できなくなりました。変更はありません。",
        @"unknownExternalVolumeUnsupported": @"バックアップ先には書き込み可能なAPFSボリュームが必要です。変更はありません。",
        @"unknownExternalVolumeChooseTitle": @"バックアップボリュームを選択",
        @"unknownExternalVolumeChooseBody": @"このディスクには使用可能なAPFSボリュームが複数あります。仮登録するボリュームを明示的に選択してください。",
        @"unknownExternalVolumeChooseAction": @"ボリュームを選択",
        @"unknownExternalVolumeChoosePlaceholder": @"ボリュームを選択してください …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — 「%2$@」としてマウント",
        @"restoreTitle": @"ファイルを復元",
        @"restoreSubtitle": @"現在および実際に利用可能な過去のコピー",
        @"restoreFilesColumn": @"ファイルとフォルダ",
        @"restoreVersionsColumn": @"利用可能なバージョン",
        @"restoreSizeColumn": @"サイズ",
        @"restoreBack": @"戻る",
        @"restoreOpenFolder": @"フォルダを開く",
        @"restoreAction": @"復元…",
        @"restoreLoading": @"バックアップを読み込み中…",
        @"restoreEmpty": @"このフォルダに復元可能なファイルはありません。",
        @"restoreTargetUnavailable": @"バックアップ先を利用できません。接続して再試行してください。",
        @"restoreCurrent": @"現在のバックアップ",
        @"restoreHistorical": @"過去のコピー",
        @"restoreVerified": @"復元し、SHA-256で検証しました。",
        @"restoreIntegrityFailed": @"復元ファイルを安全に検証できませんでした。",
        @"restoreFailed": @"ファイルを復元できませんでした。保存先とバックアップを確認してください。",
        @"restoreShowInFinder": @"Finderに表示",
        @"restoreNoVersions": @"このファイルの安全なコピーはありません。",
        @"restoreChooseDestination": @"復元ファイルの保存先フォルダを選択してください。",
        @"cancelled": @"バックアップをキャンセルしました。",
        @"cancelledHint": @"正常終了は確認されていません。",
        @"skipped": @"新しいバックアップは開始されませんでした。",
        @"skippedHint": @"バックアップはすでに実行中です。",
        @"setupTitle": @"バックアップ先と開始方法",
        @"targetType": @"アプリ/スケジュール先",
        @"destinationPreview": @"正確な保存先",
        @"externalVolume": @"外部ディスク",
        @"encryptionLabel": @"暗号化",
        @"encryptionNone": @"なし",
        @"encryptionAPFS": @"暗号化APFS",
        @"encryptionAPFSTip": @"このアプリはパスワードを読み取ったり保存したりしません。",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"鍵はrcloneが管理し、アプリはパスワードを読み取りも保存もしません。",
        @"cryptRemoteLabel": @"Cryptリモート",
        @"nas": @"NAS / ネットワーク",
        @"mountedNas": @"マウント済みNAS",
        @"refresh": @"更新",
        @"discover": @"検索",
        @"openFinder": @"Finderで開く",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"マウント先",
        @"nasSubdir": @"保存先フォルダ",
        @"schedule": @"開始",
        @"scheduleManual": @"手動のみ",
        @"scheduleLogin": @"ログイン時",
        @"scheduleHourly": @"毎時",
        @"scheduleDaily": @"毎日 20:00",
        @"save": @"保存",
        @"dryRun": @"バックアップ確認",
        @"dryRunRunning": @"確認中…",
        @"backupNow": @"今すぐバックアップ",
        @"dryRunTip": @"ファイルをコピーせず、元と保存先を確認します。",
        @"backupNowTip": @"選択した保存先へ実際のバックアップを開始します。",
        @"statusReady": @"準備完了。",
        @"statusSaved": @"保存しました。",
        @"statusSearching": @"ネットワーク検索中...",
        @"statusDiscoveryDone": @"ネットワーク検索完了。",
        @"statusBackupStarted": @"バックアップを開始しました。",
        @"statusBackupPreparing": @"バックアップを準備中…",
        @"statusDryRunStarted": @"バックアップを確認中… ファイルはコピーされません。",
        @"statusDryRunSucceeded": @"確認完了。Google Drive とバックアップ先に接続できます。",
        @"statusDryRunTargetUnavailable": @"確認失敗：バックアップ先が接続されていません。",
        @"statusDryRunFailed": @"確認に失敗しました。詳細は診断を開いてください。",
        @"statusUnsavedChanges": @"先に変更を保存してください。バックアップは開始されていません。",
        @"statusEncryptionIncompatible": @"この暗号化方式は選択した保存先では使用できません。",
        @"statusCryptRemoteInvalid": @"Google Driveリモートとは異なる安全なCryptリモート名を入力してください。",
        @"setupCheckSectionTitle": @"システム確認",
        @"setupCheckButton": @"設定を確認",
        @"setupCheckRunning": @"確認中…",
        @"setupCheckNotRun": @"まだ確認していません。",
        @"setupCheckDependenciesLabel": @"ツール",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"保存先",
        @"setupCheckDependenciesReady": @"必要なツールはすべてインストール済みです。",
        @"setupCheckDependenciesMissing": @"不足: %@。",
        @"setupCheckRemoteBlocked": @"先に不足しているツールをインストールしてください。",
        @"setupCheckRemoteMissing": @"rclone リモートが設定されていません。",
        @"setupCheckRemoteReady": @"Google Drive に接続できます。",
        @"setupCheckRemoteUnavailable": @"現在 Google Drive に接続できません。",
        @"setupCheckDestinationReady": @"保存先はマウントされ、利用できます。",
        @"setupCheckDestinationUnavailable": @"保存先が利用できないか、書き込めません。",
        @"setupCheckEncryptedAPFSRequired": @"暗号化され、ロック解除済みの APFS 保存先が必要です。",
        @"setupCheckEncryptedAPFSReady": @"暗号化 APFS 保存先を確認しました。",
        @"setupCheckRcloneCryptReady": @"rclone crypt がこの保存先全体を保護しています。",
        @"setupCheckRcloneCryptInvalid": @"Cryptリモートと暗号化オプションを確認してください。",
        @"setupCheckReady": @"設定の準備ができました。",
        @"setupCheckNeedsAttention": @"設定を確認してください。",
        @"selectMountedVolume": @"ボリュームを選択",
        @"aboutMenu": @"GDrive Backup Tigerについて",
        @"settingsMenu": @"設定...",
        @"hideMenu": @"GDrive Backup Tigerを隠す",
        @"quitMenu": @"GDrive Backup Tigerを終了",
        @"settingsTitle": @"設定",
        @"languageSetting": @"言語",
        @"cancel": @"キャンセル",
        @"done": @"完了",
        @"languageSaved": @"言語を保存しました。",
        @"overviewSubtitle": @"独立したコピー · 明確な状態 · すぐに復元",
        @"overviewLastRun": @"前回のバックアップ",
        @"overviewNextRun": @"次回の実行",
        @"overviewTarget": @"保存先",
        @"overviewStorage": @"保存先の空き容量",
        @"overviewSettings": @"バックアップを設定…",
        @"overviewOpen": @"GDrive Backup Tigerを開く",
        @"overviewNeverRun": @"バックアップはまだありません",
        @"overviewUnavailable": @"利用できません",
        @"overviewFreeOf": @"%@ 空き / %@",
        @"overviewStatusInterrupted": @"バックアップが中断されました。",
        @"overviewStatusUnknown": @"バックアップ状態は不明です。",
        @"automaticBackupsPaused": @"自動バックアップは一時停止中",
        @"pauseAutomaticBackups": @"自動バックアップを一時停止",
        @"resumeAutomaticBackups": @"自動バックアップを再開",
        @"automaticRetryRunning": @"自動再試行を実行中",
        @"automaticRetryRunningShort": @"再試行中",
        @"backupProgressCurrentPhase": @"現在の領域の進行状況",
        @"progressAreaFormat": @"領域 %1$@ / %2$@",
        @"progressPreparing": @"準備中…",
        @"progressChecking": @"変更を確認中…",
        @"progressTransferredFormat": @"%1$@ 転送 · %2$@",
        @"progressCheckedListedFormat": @"%1$@ 件確認 · %2$@ 件取得",
        @"profileLabel": @"プロファイル",
        @"profileDefault": @"デフォルト",
        @"profileCreate": @"新規プロファイル",
        @"profileRename": @"プロファイル名を変更",
        @"profileDelete": @"プロファイルを削除",
        @"profileUnsavedSwitch": @"プロファイルを切り替える前に、未保存の変更を破棄してください。",
        @"profileActivated": @"プロファイルを有効にしました。",
        @"profileNamePrompt": @"プロファイル名を入力してください。",
        @"profileDeleteConfirm": @"現在のプロファイルを削除しますか？",
        @"discardChanges": @"変更を破棄",
        @"updateCheck": @"アップデートを確認…",
        @"updateChecking": @"アップデートを確認中…",
        @"updateAvailableTitle": @"アップデートがあります",
        @"updateAvailableMessage": @"バージョン%@を利用できます。自動的なダウンロードやインストールは行いません。",
        @"updateCurrentTitle": @"最新バージョンです",
        @"updateCurrentMessage": @"バージョン%@は公開済みの最新バージョンです。",
        @"updateUnavailableTitle": @"アップデートを確認できません",
        @"updateUnavailableMessage": @"GitHubのリリースを安全に確認できませんでした。何もダウンロードしていません。",
        @"updateOpenRelease": @"GitHubリリースを開く",
        @"diagnosticsTitle": @"診断",
        @"diagnosticsSubtitle": @"システムの状態を確認し、安全なサポートレポートを作成",
        @"diagnosticsOverallReady": @"すべて準備できています。",
        @"diagnosticsOverallAttention": @"確認が必要な項目があります。",
        @"diagnosticsTools": @"ツール",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"バックアップ先",
        @"diagnosticsSchedule": @"スケジュール",
        @"diagnosticsLastRun": @"前回の実行",
        @"diagnosticsController": @"メニューバーサービス",
        @"diagnosticsScript": @"バックアップエンジン",
        @"diagnosticsReady": @"準備完了。",
        @"diagnosticsFailure": @"確認に失敗しました。",
        @"diagnosticsBlocked": @"先にツールをインストールしてください。",
        @"diagnosticsUnknown": @"未確認。",
        @"diagnosticsMissingTools": @"不足：%@",
        @"diagnosticsRefresh": @"更新",
        @"diagnosticsRefreshing": @"診断を更新中…",
        @"diagnosticsCopy": @"安全なレポートをコピー",
        @"diagnosticsSave": @"安全なレポートを保存…",
        @"diagnosticsPrivacy": @"パス、認証情報、ファイル名、ログ内容は含まれません。",
        @"diagnosticsCopied": @"安全なレポートをコピーしました。",
        @"diagnosticsSaved": @"安全なレポートを保存しました。",
        @"diagnosticsManual": @"手動のみ",
        @"diagnosticsLoaded": @"有効",
        @"diagnosticsNotLoaded": @"無効"
    };
    NSDictionary<NSString *, NSString *> *yue = @{
        @"confirmTarget": @"使用呢個卷宗？",
        @"startBackup": @"開始備份",
        @"notNow": @"暫時唔好",
        @"running": @"正在備份...",
        @"completed": @"備份完成。",
        @"runningHint": @"請勿退出磁碟。",
        @"completedHint": @"備份已完成。",
        @"backupProgress": @"備份進度",
        @"cancelBackup": @"取消備份…",
        @"cancelBackupConfirm": @"確定取消呢次備份？",
        @"cancelBackupDetail": @"進行中嘅複製會停止，現有備份會保留。",
        @"cancelBackupAction": @"取消備份",
        @"cancellingBackup": @"正在取消備份…",
        @"failed": @"備份失敗。",
        @"failedHint": @"未建立完整備份，請檢查記錄。",
        @"failedPermissionHint": @"無法寫入備份目的地，請檢查 NAS 權限。",
        @"failedNASConnectionHint": @"NAS 連線已中斷。請重新連接 NAS，再執行備份。",
        @"notifyBackupFailures": @"自動備份失敗時通知我",
        @"notifyBackupSuccesses": @"亦通知我自動備份成功",
        @"backupNotificationSuccessTitle": @"備份已成功完成",
        @"backupNotificationSuccessBody": @"自動備份已成功完成。",
        @"backupNotificationRecoverySuccessBody": @"之後的自動備份已成功完成。你的備份已再次是最新狀態。",
        @"backupNotificationRetrySuccessBody": @"自動重試已成功完成。你的備份已再次是最新狀態。",
        @"backupNotificationFailureTitle": @"自動備份失敗",
        @"backupNotificationMissedTitle": @"每日備份尚未完成",
        @"backupNotificationMissedBody": @"原定 20:00 執行的備份在 21:00 前仍未成功完成。",
        @"backupNotificationTargetUnavailable": @"備份目的地目前無法使用。請重新連接後再執行備份。",
        @"backupNotificationNASRetryBody": @"NAS 尚未完全就緒，系統將在 30 分鐘後自動重試。",
        @"backupNotificationRetryRunningTitle": @"自動備份重試進行中",
        @"backupNotificationRetryRunningBody": @"GDrive 正在再次備份。請開啟 GDrive Backup Tiger 查看進度。",
        @"backupNotificationRetryFailureBody": @"自動重試仍然失敗。請檢查 NAS 連線後再次執行備份。",
        @"unknownExternalVolumeTitle": @"偵測到新的外置磁碟",
        @"unknownExternalVolumeBody": @"「%@」未被使用，亦未開始備份。",
        @"unknownExternalVolumeSetupAction": @"設定為備份目的地",
        @"unknownExternalVolumeIgnoreAction": @"忽略",
        @"unknownExternalVolumeReviewSetup": @"「%@」只作暫存。「儲存」會將它登記為外置磁碟備份目的地；目前選擇的主要目的地維持不變。",
        @"unknownExternalVolumeUnavailable": @"磁碟已不可用，沒有作出任何更改。",
        @"unknownExternalVolumeUnsupported": @"備份目的地需要可寫入的 APFS 卷宗，沒有作出任何更改。",
        @"unknownExternalVolumeChooseTitle": @"選擇備份卷宗",
        @"unknownExternalVolumeChooseBody": @"此磁碟包含多個合適的 APFS 卷宗。請明確選擇要暫存的卷宗。",
        @"unknownExternalVolumeChooseAction": @"選擇卷宗",
        @"unknownExternalVolumeChoosePlaceholder": @"請選擇卷宗 …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — 掛載為「%2$@」",
        @"restoreTitle": @"還原檔案",
        @"restoreSubtitle": @"目前及實際可用的舊版本",
        @"restoreFilesColumn": @"檔案與資料夾",
        @"restoreVersionsColumn": @"可用版本",
        @"restoreSizeColumn": @"大小",
        @"restoreBack": @"返回",
        @"restoreOpenFolder": @"開啟資料夾",
        @"restoreAction": @"還原…",
        @"restoreLoading": @"正在讀取備份…",
        @"restoreEmpty": @"此資料夾內沒有可還原的檔案。",
        @"restoreTargetUnavailable": @"備份目的地無法使用。請重新連接後再試。",
        @"restoreCurrent": @"目前備份",
        @"restoreHistorical": @"較舊副本",
        @"restoreVerified": @"已還原並以 SHA-256 驗證。",
        @"restoreIntegrityFailed": @"無法安全驗證已還原的檔案。",
        @"restoreFailed": @"無法還原檔案。請檢查目的地及備份。",
        @"restoreShowInFinder": @"在 Finder 顯示",
        @"restoreNoVersions": @"此檔案沒有可用的安全副本。",
        @"restoreChooseDestination": @"請選擇還原檔案的儲存資料夾。",
        @"cancelled": @"備份已取消。",
        @"cancelledHint": @"未確認成功完成。",
        @"skipped": @"未開始新備份。",
        @"skippedHint": @"備份已經進行中。",
        @"setupTitle": @"備份目的地同啟動方式",
        @"targetType": @"App/排程目的地",
        @"destinationPreview": @"確實目的地",
        @"externalVolume": @"外置磁碟",
        @"encryptionLabel": @"加密",
        @"encryptionNone": @"無",
        @"encryptionAPFS": @"加密 APFS",
        @"encryptionAPFSTip": @"App 唔會讀取或儲存任何密碼。",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"密鑰由 rclone 管理；App 唔會讀取或儲存密碼。",
        @"cryptRemoteLabel": @"Crypt Remote",
        @"nas": @"NAS / 網絡",
        @"mountedNas": @"已掛載 NAS",
        @"refresh": @"重新整理",
        @"discover": @"搜尋",
        @"openFinder": @"喺 Finder 開啟",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"掛載點",
        @"nasSubdir": @"目的地資料夾",
        @"schedule": @"啟動",
        @"scheduleManual": @"只限手動",
        @"scheduleLogin": @"登入時",
        @"scheduleHourly": @"每小時",
        @"scheduleDaily": @"每日 20:00",
        @"save": @"儲存",
        @"dryRun": @"檢查備份",
        @"dryRunRunning": @"檢查緊…",
        @"backupNow": @"即刻備份",
        @"dryRunTip": @"只檢查來源同目的地，唔會複製檔案。",
        @"backupNowTip": @"開始真正備份到已選目的地。",
        @"statusReady": @"準備好。",
        @"statusSaved": @"已儲存。",
        @"statusSearching": @"搜尋網絡中...",
        @"statusDiscoveryDone": @"網絡搜尋完成。",
        @"statusBackupStarted": @"備份已開始。",
        @"statusBackupPreparing": @"正在準備備份…",
        @"statusDryRunStarted": @"檢查緊備份… 唔會複製檔案。",
        @"statusDryRunSucceeded": @"檢查完成。Google Drive 同備份目的地都連接到。",
        @"statusDryRunTargetUnavailable": @"檢查失敗：備份目的地未連接。",
        @"statusDryRunFailed": @"檢查失敗。請開啟診斷睇詳情。",
        @"statusUnsavedChanges": @"請先儲存變更，未有開始備份。",
        @"statusEncryptionIncompatible": @"呢種加密模式唔適用於所選目的地。",
        @"statusCryptRemoteInvalid": @"請輸入安全而且唔同於 Google Drive Remote 嘅 Crypt Remote 名稱。",
        @"setupCheckSectionTitle": @"系統檢查",
        @"setupCheckButton": @"檢查設定",
        @"setupCheckRunning": @"正在檢查…",
        @"setupCheckNotRun": @"尚未檢查。",
        @"setupCheckDependenciesLabel": @"工具",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"備份目的地",
        @"setupCheckDependenciesReady": @"所需工具已全部安裝。",
        @"setupCheckDependenciesMissing": @"欠缺：%@。",
        @"setupCheckRemoteBlocked": @"請先安裝欠缺的工具。",
        @"setupCheckRemoteMissing": @"尚未設定 rclone remote。",
        @"setupCheckRemoteReady": @"可以連接 Google Drive。",
        @"setupCheckRemoteUnavailable": @"目前無法連接 Google Drive。",
        @"setupCheckDestinationReady": @"目的地已掛載並可存取。",
        @"setupCheckDestinationUnavailable": @"目的地不可用或無法寫入。",
        @"setupCheckEncryptedAPFSRequired": @"需要已加密並解鎖的 APFS 目的地。",
        @"setupCheckEncryptedAPFSReady": @"已確認加密 APFS 目的地。",
        @"setupCheckRcloneCryptReady": @"rclone crypt 已完整保護此目的地。",
        @"setupCheckRcloneCryptInvalid": @"請檢查 Crypt Remote 同加密選項。",
        @"setupCheckReady": @"設定已準備好。",
        @"setupCheckNeedsAttention": @"設定需要處理。",
        @"selectMountedVolume": @"選擇卷宗",
        @"aboutMenu": @"關於 GDrive Backup Tiger",
        @"settingsMenu": @"設定...",
        @"hideMenu": @"隱藏 GDrive Backup Tiger",
        @"quitMenu": @"結束 GDrive Backup Tiger",
        @"settingsTitle": @"設定",
        @"languageSetting": @"語言",
        @"cancel": @"取消",
        @"done": @"完成",
        @"languageSaved": @"語言已儲存。",
        @"overviewSubtitle": @"獨立副本 · 狀態清楚 · 隨時可還原",
        @"overviewLastRun": @"上次備份",
        @"overviewNextRun": @"下次執行",
        @"overviewTarget": @"目的地",
        @"overviewStorage": @"目的地可用空間",
        @"overviewSettings": @"設定備份…",
        @"overviewOpen": @"開啟 GDrive Backup Tiger",
        @"overviewNeverRun": @"仲未有備份",
        @"overviewUnavailable": @"無法使用",
        @"overviewFreeOf": @"%@ 可用，共 %@",
        @"overviewStatusInterrupted": @"備份已中斷。",
        @"overviewStatusUnknown": @"備份狀態不明。",
        @"automaticBackupsPaused": @"自動備份已暫停",
        @"pauseAutomaticBackups": @"暫停自動備份",
        @"resumeAutomaticBackups": @"繼續自動備份",
        @"automaticRetryRunning": @"自動重試進行中",
        @"automaticRetryRunningShort": @"重試中",
        @"backupProgressCurrentPhase": @"目前區域嘅進度",
        @"progressAreaFormat": @"區域 %1$@ / %2$@",
        @"progressPreparing": @"準備中…",
        @"progressChecking": @"正在檢查變更…",
        @"progressTransferredFormat": @"已傳送 %1$@ · %2$@",
        @"progressCheckedListedFormat": @"已檢查 %1$@ 項 · 已列出 %2$@ 項",
        @"profileLabel": @"設定檔",
        @"profileDefault": @"預設",
        @"profileCreate": @"新增設定檔",
        @"profileRename": @"重新命名設定檔",
        @"profileDelete": @"刪除設定檔",
        @"profileUnsavedSwitch": @"切換設定檔前，必須捨棄未儲存的變更。",
        @"profileActivated": @"設定檔已啟用。",
        @"profileNamePrompt": @"輸入設定檔名稱。",
        @"profileDeleteConfirm": @"要刪除目前的設定檔嗎？",
        @"discardChanges": @"捨棄變更",
        @"updateCheck": @"檢查更新…",
        @"updateChecking": @"正在檢查更新…",
        @"updateAvailableTitle": @"有可用更新",
        @"updateAvailableMessage": @"版本 %@ 已推出。程式不會自動下載或安裝任何內容。",
        @"updateCurrentTitle": @"已是最新版本",
        @"updateCurrentMessage": @"版本 %@ 已是最新發布版本。",
        @"updateUnavailableTitle": @"無法檢查更新",
        @"updateUnavailableMessage": @"目前無法安全檢查 GitHub 發布版本，並未下載任何內容。",
        @"updateOpenRelease": @"開啟 GitHub 發布頁面",
        @"diagnosticsTitle": @"診斷",
        @"diagnosticsSubtitle": @"檢查系統狀態並建立安全支援報告",
        @"diagnosticsOverallReady": @"全部準備就緒。",
        @"diagnosticsOverallAttention": @"部分項目需要注意。",
        @"diagnosticsTools": @"工具",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"備份目的地",
        @"diagnosticsSchedule": @"排程",
        @"diagnosticsLastRun": @"上次執行",
        @"diagnosticsController": @"選單列服務",
        @"diagnosticsScript": @"備份引擎",
        @"diagnosticsReady": @"準備就緒。",
        @"diagnosticsFailure": @"檢查失敗。",
        @"diagnosticsBlocked": @"請先安裝工具。",
        @"diagnosticsUnknown": @"尚未檢查。",
        @"diagnosticsMissingTools": @"欠缺：%@",
        @"diagnosticsRefresh": @"更新",
        @"diagnosticsRefreshing": @"正在更新診斷…",
        @"diagnosticsCopy": @"複製安全報告",
        @"diagnosticsSave": @"儲存安全報告…",
        @"diagnosticsPrivacy": @"不包含路徑、登入資料、檔案名稱或記錄內容。",
        @"diagnosticsCopied": @"已複製安全報告。",
        @"diagnosticsSaved": @"已儲存安全報告。",
        @"diagnosticsManual": @"只限手動",
        @"diagnosticsLoaded": @"已啟用",
        @"diagnosticsNotLoaded": @"未啟用"
    };
    NSDictionary<NSString *, NSString *> *ko = @{
        @"confirmTarget": @"이 볼륨을 사용할까요?",
        @"startBackup": @"백업 시작",
        @"notNow": @"지금 안 함",
        @"running": @"백업 중...",
        @"completed": @"백업 완료.",
        @"runningHint": @"디스크를 꺼내지 마세요.",
        @"completedHint": @"백업이 완료되었습니다.",
        @"backupProgress": @"백업 진행률",
        @"cancelBackup": @"백업 취소…",
        @"cancelBackupConfirm": @"이 백업을 취소할까요?",
        @"cancelBackupDetail": @"진행 중인 복사를 중단합니다. 기존 백업은 유지됩니다.",
        @"cancelBackupAction": @"백업 취소",
        @"cancellingBackup": @"백업 취소 중…",
        @"failed": @"백업에 실패했습니다.",
        @"failedHint": @"완전한 백업이 생성되지 않았습니다. 로그를 확인하세요.",
        @"failedPermissionHint": @"대상에 쓸 수 없습니다. NAS 권한을 확인하세요.",
        @"failedNASConnectionHint": @"NAS 연결이 끊겼습니다. NAS를 다시 연결한 뒤 백업을 다시 실행하세요.",
        @"notifyBackupFailures": @"자동 백업 실패 시 알림",
        @"notifyBackupSuccesses": @"자동 백업 성공도 알림",
        @"backupNotificationSuccessTitle": @"백업이 성공적으로 완료되었습니다",
        @"backupNotificationSuccessBody": @"자동 백업이 성공적으로 완료되었습니다.",
        @"backupNotificationRecoverySuccessBody": @"이후 자동 백업이 성공적으로 완료되었습니다. 백업이 다시 최신 상태입니다.",
        @"backupNotificationRetrySuccessBody": @"자동 재시도가 성공적으로 완료되었습니다. 백업이 다시 최신 상태입니다.",
        @"backupNotificationFailureTitle": @"자동 백업 실패",
        @"backupNotificationMissedTitle": @"일일 백업 누락",
        @"backupNotificationMissedBody": @"20:00에 예약된 백업이 21:00까지 성공적으로 완료되지 않았습니다.",
        @"backupNotificationTargetUnavailable": @"백업 대상에 연결할 수 없습니다. 다시 연결한 뒤 백업을 실행하세요.",
        @"backupNotificationNASRetryBody": @"NAS가 아직 완전히 준비되지 않았습니다. 30분 후 자동으로 다시 시도합니다.",
        @"backupNotificationRetryRunningTitle": @"자동 백업 재시도 실행 중",
        @"backupNotificationRetryRunningBody": @"GDrive를 다시 백업하고 있습니다. 진행 상황을 보려면 GDrive Backup Tiger를 여십시오.",
        @"backupNotificationRetryFailureBody": @"자동 재시도도 실패했습니다. NAS 연결을 확인한 뒤 백업을 다시 실행하세요.",
        @"unknownExternalVolumeTitle": @"새 외장 디스크 감지됨",
        @"unknownExternalVolumeBody": @"‘%@’은(는) 사용되지 않습니다. 백업을 시작하지 않았습니다.",
        @"unknownExternalVolumeSetupAction": @"백업 대상으로 설정",
        @"unknownExternalVolumeIgnoreAction": @"무시",
        @"unknownExternalVolumeReviewSetup": @"‘%@’은(는) 임시 등록 상태입니다. 저장하면 외장 디스크 백업 대상으로 등록되며, 현재 선택한 기본 대상은 바뀌지 않습니다.",
        @"unknownExternalVolumeUnavailable": @"디스크를 더 이상 사용할 수 없습니다. 변경된 내용이 없습니다.",
        @"unknownExternalVolumeUnsupported": @"백업 대상에는 쓰기 가능한 APFS 볼륨이 필요합니다. 변경된 내용이 없습니다.",
        @"unknownExternalVolumeChooseTitle": @"백업 볼륨 선택",
        @"unknownExternalVolumeChooseBody": @"이 디스크에는 적합한 APFS 볼륨이 여러 개 있습니다. 임시 등록할 볼륨을 명시적으로 선택하십시오.",
        @"unknownExternalVolumeChooseAction": @"볼륨 선택",
        @"unknownExternalVolumeChoosePlaceholder": @"볼륨을 선택하십시오 …",
        @"unknownExternalVolumeChoiceLabelFormat": @"%1$@ — ‘%2$@’(으)로 마운트됨",
        @"restoreTitle": @"파일 복원",
        @"restoreSubtitle": @"현재 및 실제로 사용 가능한 이전 사본",
        @"restoreFilesColumn": @"파일 및 폴더",
        @"restoreVersionsColumn": @"사용 가능한 버전",
        @"restoreSizeColumn": @"크기",
        @"restoreBack": @"뒤로",
        @"restoreOpenFolder": @"폴더 열기",
        @"restoreAction": @"복원…",
        @"restoreLoading": @"백업 읽는 중…",
        @"restoreEmpty": @"이 폴더에 복원할 수 있는 파일이 없습니다.",
        @"restoreTargetUnavailable": @"백업 대상에 연결할 수 없습니다. 다시 연결한 후 시도하세요.",
        @"restoreCurrent": @"현재 백업",
        @"restoreHistorical": @"이전 사본",
        @"restoreVerified": @"복원 후 SHA-256으로 검증했습니다.",
        @"restoreIntegrityFailed": @"복원된 파일을 안전하게 검증할 수 없습니다.",
        @"restoreFailed": @"파일을 복원할 수 없습니다. 대상과 백업을 확인하세요.",
        @"restoreShowInFinder": @"Finder에서 보기",
        @"restoreNoVersions": @"이 파일의 안전한 사본이 없습니다.",
        @"restoreChooseDestination": @"복원된 파일을 저장할 폴더를 선택하세요.",
        @"cancelled": @"백업이 취소되었습니다.",
        @"cancelledHint": @"성공적인 완료가 확인되지 않았습니다.",
        @"skipped": @"새 백업을 시작하지 않았습니다.",
        @"skippedHint": @"백업이 이미 실행 중입니다.",
        @"setupTitle": @"백업 대상 및 시작 방식",
        @"targetType": @"앱/예약 대상",
        @"destinationPreview": @"정확한 대상",
        @"externalVolume": @"외장 디스크",
        @"encryptionLabel": @"암호화",
        @"encryptionNone": @"없음",
        @"encryptionAPFS": @"암호화 APFS",
        @"encryptionAPFSTip": @"앱은 암호를 읽거나 저장하지 않습니다.",
        @"encryptionRcloneCrypt": @"rclone crypt",
        @"encryptionRcloneTip": @"키는 rclone이 관리하며 앱은 암호를 읽거나 저장하지 않습니다.",
        @"cryptRemoteLabel": @"Crypt 원격",
        @"nas": @"NAS / 네트워크",
        @"mountedNas": @"마운트된 NAS",
        @"refresh": @"새로 고침",
        @"discover": @"검색",
        @"openFinder": @"Finder에서 열기",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"마운트 지점",
        @"nasSubdir": @"대상 폴더",
        @"schedule": @"시작",
        @"scheduleManual": @"수동만",
        @"scheduleLogin": @"로그인 시",
        @"scheduleHourly": @"매시간",
        @"scheduleDaily": @"매일 20:00",
        @"save": @"저장",
        @"dryRun": @"백업 확인",
        @"dryRunRunning": @"확인 중…",
        @"backupNow": @"지금 백업",
        @"dryRunTip": @"파일을 복사하지 않고 원본과 대상을 확인합니다.",
        @"backupNowTip": @"선택한 대상에 실제 백업을 시작합니다.",
        @"statusReady": @"준비됨.",
        @"statusSaved": @"저장됨.",
        @"statusSearching": @"네트워크 검색 중...",
        @"statusDiscoveryDone": @"네트워크 검색 완료.",
        @"statusBackupStarted": @"백업 시작됨.",
        @"statusBackupPreparing": @"백업 준비 중…",
        @"statusDryRunStarted": @"백업 확인 중… 파일은 복사되지 않습니다.",
        @"statusDryRunSucceeded": @"확인 완료. Google Drive와 백업 대상에 연결할 수 있습니다.",
        @"statusDryRunTargetUnavailable": @"확인 실패: 백업 대상이 연결되어 있지 않습니다.",
        @"statusDryRunFailed": @"확인에 실패했습니다. 자세한 내용은 진단을 여세요.",
        @"statusUnsavedChanges": @"먼저 변경 사항을 저장하세요. 백업은 시작되지 않았습니다.",
        @"statusEncryptionIncompatible": @"이 암호화 방식은 선택한 대상과 호환되지 않습니다.",
        @"statusCryptRemoteInvalid": @"Google Drive 원격과 다른 안전한 Crypt 원격 이름을 입력하십시오.",
        @"setupCheckSectionTitle": @"시스템 확인",
        @"setupCheckButton": @"설정 확인",
        @"setupCheckRunning": @"확인 중…",
        @"setupCheckNotRun": @"아직 확인하지 않았습니다.",
        @"setupCheckDependenciesLabel": @"도구",
        @"setupCheckRemoteLabel": @"Google Drive",
        @"setupCheckDestinationLabel": @"백업 대상",
        @"setupCheckDependenciesReady": @"필요한 도구가 모두 설치되어 있습니다.",
        @"setupCheckDependenciesMissing": @"누락: %@.",
        @"setupCheckRemoteBlocked": @"먼저 누락된 도구를 설치하세요.",
        @"setupCheckRemoteMissing": @"rclone remote가 설정되지 않았습니다.",
        @"setupCheckRemoteReady": @"Google Drive에 연결할 수 있습니다.",
        @"setupCheckRemoteUnavailable": @"현재 Google Drive에 연결할 수 없습니다.",
        @"setupCheckDestinationReady": @"대상이 마운트되어 접근할 수 있습니다.",
        @"setupCheckDestinationUnavailable": @"대상을 사용할 수 없거나 쓸 수 없습니다.",
        @"setupCheckEncryptedAPFSRequired": @"암호화되고 잠금 해제된 APFS 대상이 필요합니다.",
        @"setupCheckEncryptedAPFSReady": @"암호화된 APFS 대상을 확인했습니다.",
        @"setupCheckRcloneCryptReady": @"rclone crypt가 이 대상을 완전히 보호합니다.",
        @"setupCheckRcloneCryptInvalid": @"Crypt 원격과 암호화 옵션을 확인하십시오.",
        @"setupCheckReady": @"설정이 준비되었습니다.",
        @"setupCheckNeedsAttention": @"설정을 확인해야 합니다.",
        @"selectMountedVolume": @"볼륨 선택",
        @"aboutMenu": @"GDrive Backup Tiger 정보",
        @"settingsMenu": @"설정...",
        @"hideMenu": @"GDrive Backup Tiger 가리기",
        @"quitMenu": @"GDrive Backup Tiger 종료",
        @"settingsTitle": @"설정",
        @"languageSetting": @"언어",
        @"cancel": @"취소",
        @"done": @"완료",
        @"languageSaved": @"언어가 저장되었습니다.",
        @"overviewSubtitle": @"독립 사본 · 명확한 상태 · 바로 복원",
        @"overviewLastRun": @"최근 백업",
        @"overviewNextRun": @"다음 실행",
        @"overviewTarget": @"대상",
        @"overviewStorage": @"대상 여유 공간",
        @"overviewSettings": @"백업 설정…",
        @"overviewOpen": @"GDrive Backup Tiger 열기",
        @"overviewNeverRun": @"아직 백업 없음",
        @"overviewUnavailable": @"사용할 수 없음",
        @"overviewFreeOf": @"%@ 사용 가능 / %@",
        @"overviewStatusInterrupted": @"백업이 중단되었습니다.",
        @"overviewStatusUnknown": @"백업 상태를 알 수 없습니다.",
        @"automaticBackupsPaused": @"자동 백업 일시 정지됨",
        @"pauseAutomaticBackups": @"자동 백업 일시 정지",
        @"resumeAutomaticBackups": @"자동 백업 재개",
        @"automaticRetryRunning": @"자동 재시도 실행 중",
        @"automaticRetryRunningShort": @"재시도 중",
        @"backupProgressCurrentPhase": @"현재 영역 진행률",
        @"progressAreaFormat": @"영역 %1$@/%2$@",
        @"progressPreparing": @"준비 중…",
        @"progressChecking": @"변경 사항 확인 중…",
        @"progressTransferredFormat": @"%1$@ 전송 · %2$@",
        @"progressCheckedListedFormat": @"%1$@개 확인 · %2$@개 검색",
        @"profileLabel": @"프로필",
        @"profileDefault": @"기본값",
        @"profileCreate": @"새 프로필",
        @"profileRename": @"프로필 이름 변경",
        @"profileDelete": @"프로필 삭제",
        @"profileUnsavedSwitch": @"프로필을 전환하기 전에 저장하지 않은 변경 사항을 버려야 합니다.",
        @"profileActivated": @"프로필이 활성화되었습니다.",
        @"profileNamePrompt": @"프로필 이름을 입력하세요.",
        @"profileDeleteConfirm": @"현재 프로필을 삭제할까요?",
        @"discardChanges": @"변경 사항 버리기",
        @"updateCheck": @"업데이트 확인…",
        @"updateChecking": @"업데이트 확인 중…",
        @"updateAvailableTitle": @"업데이트 사용 가능",
        @"updateAvailableMessage": @"버전 %@을 사용할 수 있습니다. 앱은 자동으로 다운로드하거나 설치하지 않습니다.",
        @"updateCurrentTitle": @"최신 버전입니다",
        @"updateCurrentMessage": @"버전 %@은 이미 최신 공개 버전입니다.",
        @"updateUnavailableTitle": @"업데이트를 확인할 수 없음",
        @"updateUnavailableMessage": @"현재 GitHub 릴리스를 안전하게 확인할 수 없습니다. 아무것도 다운로드하지 않았습니다.",
        @"updateOpenRelease": @"GitHub 릴리스 열기",
        @"diagnosticsTitle": @"진단",
        @"diagnosticsSubtitle": @"시스템 상태를 확인하고 안전한 지원 보고서 생성",
        @"diagnosticsOverallReady": @"모두 준비되었습니다.",
        @"diagnosticsOverallAttention": @"확인이 필요한 항목이 있습니다.",
        @"diagnosticsTools": @"도구",
        @"diagnosticsRemote": @"Google Drive",
        @"diagnosticsDestination": @"백업 대상",
        @"diagnosticsSchedule": @"일정",
        @"diagnosticsLastRun": @"최근 실행",
        @"diagnosticsController": @"메뉴 막대 서비스",
        @"diagnosticsScript": @"백업 엔진",
        @"diagnosticsReady": @"준비됨.",
        @"diagnosticsFailure": @"확인에 실패했습니다.",
        @"diagnosticsBlocked": @"먼저 도구를 설치하세요.",
        @"diagnosticsUnknown": @"확인하지 않음.",
        @"diagnosticsMissingTools": @"누락: %@",
        @"diagnosticsRefresh": @"새로 고침",
        @"diagnosticsRefreshing": @"진단 업데이트 중…",
        @"diagnosticsCopy": @"안전한 보고서 복사",
        @"diagnosticsSave": @"안전한 보고서 저장…",
        @"diagnosticsPrivacy": @"경로, 자격 증명, 파일 이름 또는 로그 내용은 포함되지 않습니다.",
        @"diagnosticsCopied": @"안전한 보고서를 복사했습니다.",
        @"diagnosticsSaved": @"안전한 보고서를 저장했습니다.",
        @"diagnosticsManual": @"수동만",
        @"diagnosticsLoaded": @"활성",
        @"diagnosticsNotLoaded": @"비활성"
    };

    NSDictionary<NSString *, NSDictionary<NSString *, NSString *> *> *tables = @{
        @"de": de,
        @"en": en,
        @"fr": fr,
        @"es": es,
        @"ja": ja,
        @"yue": yue,
        @"ko": ko
    };
    return (tables[language][key] ?: en[key]) ?: key;
}

NSArray<NSString *> *SupportedLanguageCodes(void) {
    return @[@"de", @"en", @"fr", @"es", @"ja", @"yue", @"ko"];
}

NSString *LanguageDisplayName(NSString *code) {
    NSDictionary<NSString *, NSString *> *names = @{
        @"de": @"Deutsch",
        @"en": @"English",
        @"fr": @"Français",
        @"es": @"Español",
        @"ja": @"日本語",
        @"yue": @"粵語",
        @"ko": @"한국어"
    };
    return names[code] ?: @"English";
}
