#import "Localization.h"

#import "ConfigSupport.h"

NSString *ConfiguredLanguage(void) {
    NSString *value = [GDTReadConfigDictionary()[@"GDRIVE_BACKUP_LANG"] ?: @"" lowercaseString];
    for (NSString *code in SupportedLanguageCodes()) {
        if ([value isEqualToString:code] || [value hasPrefix:[code stringByAppendingString:@"-"]] || [value hasPrefix:[code stringByAppendingString:@"_"]]) {
            return code;
        }
    }
    if ([value hasPrefix:@"zh-hk"] || [value hasPrefix:@"zh_hk"] || [value hasPrefix:@"zh-hant-hk"] || [value hasPrefix:@"zh_hant_hk"] || [value hasPrefix:@"zh-mo"] || [value hasPrefix:@"zh_mo"]) {
        return @"yue";
    }

    NSString *preferred = NSLocale.preferredLanguages.firstObject.lowercaseString;
    if ([preferred hasPrefix:@"de"]) return @"de";
    if ([preferred hasPrefix:@"fr"]) return @"fr";
    if ([preferred hasPrefix:@"es"]) return @"es";
    if ([preferred hasPrefix:@"ja"]) return @"ja";
    if ([preferred hasPrefix:@"ko"]) return @"ko";
    if ([preferred hasPrefix:@"yue"] || [preferred hasPrefix:@"zh-hk"] || [preferred hasPrefix:@"zh_hk"] || [preferred hasPrefix:@"zh-hant-hk"] || [preferred hasPrefix:@"zh_hant_hk"] || [preferred hasPrefix:@"zh-mo"] || [preferred hasPrefix:@"zh_mo"]) return @"yue";
    return @"en";
}

NSString *T(NSString *language, NSString *key) {
    NSDictionary<NSString *, NSString *> *de = @{
        @"confirmTarget": @"Dieses Volume verwenden?",
        @"startBackup": @"Backup starten",
        @"notNow": @"Nicht jetzt",
        @"running": @"Sicherung wird erstellt ...",
        @"completed": @"Sicherung abgeschlossen.",
        @"runningHint": @"Bitte Festplatte nicht auswerfen.",
        @"completedHint": @"Backup ist fertig.",
        @"backupProgress": @"Sicherungsfortschritt",
        @"failed": @"Sicherung fehlgeschlagen.",
        @"failedHint": @"Keine vollständige Sicherung erstellt. Protokoll prüfen.",
        @"failedPermissionHint": @"Ziel nicht beschreibbar. NAS-Zugriffsrechte prüfen.",
        @"cancelled": @"Sicherung abgebrochen.",
        @"cancelledHint": @"Es wurde kein erfolgreicher Abschluss bestätigt.",
        @"skipped": @"Keine neue Sicherung gestartet.",
        @"skippedHint": @"Eine Sicherung läuft bereits.",
        @"setupTitle": @"Backup-Ziel und Startmodus",
        @"targetType": @"App-/Zeitplan-Ziel",
        @"destinationPreview": @"Genaues Ziel",
        @"externalVolume": @"Externe Platte",
        @"encryptionAPFS": @"Verschlüsseltes APFS voraussetzen (bereits entsperrt)",
        @"encryptionAPFSTip": @"Die App liest oder speichert kein Passwort.",
        @"nas": @"NAS / Netzwerk",
        @"mountedNas": @"Gemountete NAS",
        @"refresh": @"Aktualisieren",
        @"discover": @"Suchen",
        @"openFinder": @"Im Finder öffnen",
        @"nasUrl": @"NAS-URL",
        @"nasMount": @"Mountpunkt",
        @"nasSubdir": @"Zielordner",
        @"schedule": @"Starten",
        @"scheduleManual": @"Nur manuell",
        @"scheduleLogin": @"Beim Login",
        @"scheduleHourly": @"Stündlich",
        @"scheduleDaily": @"Täglich 20:00",
        @"save": @"Speichern",
        @"dryRun": @"Backup prüfen",
        @"backupNow": @"Backup jetzt",
        @"dryRunTip": @"Prüft Quelle und Ziel, ohne Dateien zu kopieren.",
        @"backupNowTip": @"Startet das echte Backup und schreibt auf das gewählte Ziel.",
        @"statusReady": @"Bereit.",
        @"statusSaved": @"Gespeichert.",
        @"statusSearching": @"Suche im Netzwerk ...",
        @"statusDiscoveryDone": @"Netzwerksuche abgeschlossen.",
        @"statusBackupStarted": @"Backup gestartet.",
        @"statusBackupPreparing": @"Backup wird vorbereitet …",
        @"statusDryRunStarted": @"Prüflauf gestartet. Es wird nichts kopiert.",
        @"statusUnsavedChanges": @"Änderungen zuerst speichern. Es wurde kein Backup gestartet.",
        @"selectMountedVolume": @"Volume auswählen",
        @"aboutMenu": @"Über GDrive Backup Tiger",
        @"settingsMenu": @"Einstellungen ...",
        @"hideMenu": @"GDrive Backup Tiger ausblenden",
        @"quitMenu": @"GDrive Backup Tiger beenden",
        @"settingsTitle": @"Einstellungen",
        @"languageSetting": @"Sprache",
        @"cancel": @"Abbrechen",
        @"done": @"Fertig",
        @"languageSaved": @"Sprache gespeichert.",
        @"overviewSubtitle": @"Unabhängige Kopie · klarer Status · bereit zum Wiederherstellen",
        @"overviewLastRun": @"Letztes Backup",
        @"overviewNextRun": @"Nächster Lauf",
        @"overviewTarget": @"Ziel",
        @"overviewStorage": @"Speicher",
        @"overviewSettings": @"Backup einrichten …",
        @"overviewOpen": @"GDrive Backup Tiger öffnen",
        @"overviewNeverRun": @"Noch kein Backup",
        @"overviewUnavailable": @"Nicht verfügbar",
        @"overviewFreeOf": @"%@ frei von %@",
        @"overviewStatusInterrupted": @"Sicherung wurde unterbrochen.",
        @"overviewStatusUnknown": @"Backup-Status unbekannt."
    };
    NSDictionary<NSString *, NSString *> *en = @{
        @"confirmTarget": @"Use this volume?",
        @"startBackup": @"Start backup",
        @"notNow": @"Not now",
        @"running": @"Backup is running ...",
        @"completed": @"Backup completed.",
        @"runningHint": @"Please do not eject the disk.",
        @"completedHint": @"Backup is done.",
        @"backupProgress": @"Backup progress",
        @"failed": @"Backup failed.",
        @"failedHint": @"No complete backup was created. Check the log.",
        @"failedPermissionHint": @"Target is not writable. Check NAS permissions.",
        @"cancelled": @"Backup cancelled.",
        @"cancelledHint": @"A successful completion was not confirmed.",
        @"skipped": @"No new backup started.",
        @"skippedHint": @"A backup is already running.",
        @"setupTitle": @"Backup target and trigger",
        @"targetType": @"App/schedule target",
        @"destinationPreview": @"Exact destination",
        @"externalVolume": @"External disk",
        @"encryptionAPFS": @"Require encrypted APFS (already unlocked)",
        @"encryptionAPFSTip": @"The app does not read or store a password.",
        @"nas": @"NAS / Network",
        @"mountedNas": @"Mounted NAS",
        @"refresh": @"Refresh",
        @"discover": @"Search",
        @"openFinder": @"Open in Finder",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"Mount point",
        @"nasSubdir": @"Destination folder",
        @"schedule": @"Start",
        @"scheduleManual": @"Manual only",
        @"scheduleLogin": @"At login",
        @"scheduleHourly": @"Hourly",
        @"scheduleDaily": @"Daily 20:00",
        @"save": @"Save",
        @"dryRun": @"Check backup",
        @"backupNow": @"Back up now",
        @"dryRunTip": @"Checks source and destination without copying files.",
        @"backupNowTip": @"Starts the real backup and writes to the selected destination.",
        @"statusReady": @"Ready.",
        @"statusSaved": @"Saved.",
        @"statusSearching": @"Searching network ...",
        @"statusDiscoveryDone": @"Network search completed.",
        @"statusBackupStarted": @"Backup started.",
        @"statusBackupPreparing": @"Preparing backup …",
        @"statusDryRunStarted": @"Check started. No files will be copied.",
        @"statusUnsavedChanges": @"Save changes first. No backup was started.",
        @"selectMountedVolume": @"Select volume",
        @"aboutMenu": @"About GDrive Backup Tiger",
        @"settingsMenu": @"Settings ...",
        @"hideMenu": @"Hide GDrive Backup Tiger",
        @"quitMenu": @"Quit GDrive Backup Tiger",
        @"settingsTitle": @"Settings",
        @"languageSetting": @"Language",
        @"cancel": @"Cancel",
        @"done": @"Done",
        @"languageSaved": @"Language saved.",
        @"overviewSubtitle": @"Independent copy · clear status · ready to restore",
        @"overviewLastRun": @"Last backup",
        @"overviewNextRun": @"Next run",
        @"overviewTarget": @"Destination",
        @"overviewStorage": @"Storage",
        @"overviewSettings": @"Set up backup …",
        @"overviewOpen": @"Open GDrive Backup Tiger",
        @"overviewNeverRun": @"No backup yet",
        @"overviewUnavailable": @"Not available",
        @"overviewFreeOf": @"%@ free of %@",
        @"overviewStatusInterrupted": @"Backup was interrupted.",
        @"overviewStatusUnknown": @"Backup status unknown."
    };
    NSDictionary<NSString *, NSString *> *fr = @{
        @"confirmTarget": @"Utiliser ce volume ?",
        @"startBackup": @"Sauvegarder",
        @"notNow": @"Pas maintenant",
        @"running": @"Sauvegarde en cours ...",
        @"completed": @"Sauvegarde terminée.",
        @"runningHint": @"Veuillez ne pas éjecter le disque.",
        @"completedHint": @"Sauvegarde terminée.",
        @"backupProgress": @"Progression de la sauvegarde",
        @"failed": @"Échec de la sauvegarde.",
        @"failedHint": @"Aucune sauvegarde complète. Consultez le journal.",
        @"failedPermissionHint": @"Cible non accessible en écriture. Vérifiez les droits NAS.",
        @"cancelled": @"Sauvegarde annulée.",
        @"cancelledHint": @"Aucune fin réussie n’a été confirmée.",
        @"skipped": @"Aucune nouvelle sauvegarde lancée.",
        @"skippedHint": @"Une sauvegarde est déjà en cours.",
        @"setupTitle": @"Destination et mode de démarrage",
        @"targetType": @"Destination app/planifiée",
        @"destinationPreview": @"Destination exacte",
        @"externalVolume": @"Disque externe",
        @"encryptionAPFS": @"Exiger un APFS chiffré (déjà déverrouillé)",
        @"encryptionAPFSTip": @"L’app ne lit ni n’enregistre aucun mot de passe.",
        @"nas": @"NAS / Réseau",
        @"mountedNas": @"NAS monté",
        @"refresh": @"Actualiser",
        @"discover": @"Rechercher",
        @"openFinder": @"Ouvrir dans le Finder",
        @"nasUrl": @"URL du NAS",
        @"nasMount": @"Point de montage",
        @"nasSubdir": @"Dossier cible",
        @"schedule": @"Démarrage",
        @"scheduleManual": @"Manuel uniquement",
        @"scheduleLogin": @"À la connexion",
        @"scheduleHourly": @"Toutes les heures",
        @"scheduleDaily": @"Tous les jours 20:00",
        @"save": @"Enregistrer",
        @"dryRun": @"Vérifier la sauvegarde",
        @"backupNow": @"Sauvegarder",
        @"dryRunTip": @"Vérifie la source et la destination sans copier de fichiers.",
        @"backupNowTip": @"Lance la vraie sauvegarde vers la destination choisie.",
        @"statusReady": @"Prêt.",
        @"statusSaved": @"Enregistré.",
        @"statusSearching": @"Recherche sur le réseau ...",
        @"statusDiscoveryDone": @"Recherche réseau terminée.",
        @"statusBackupStarted": @"Sauvegarde lancée.",
        @"statusBackupPreparing": @"Préparation de la sauvegarde…",
        @"statusDryRunStarted": @"Vérification lancée. Aucun fichier ne sera copié.",
        @"statusUnsavedChanges": @"Enregistrez d’abord les modifications. Aucune sauvegarde lancée.",
        @"selectMountedVolume": @"Choisir un volume",
        @"aboutMenu": @"À propos de GDrive Backup Tiger",
        @"settingsMenu": @"Réglages ...",
        @"hideMenu": @"Masquer GDrive Backup Tiger",
        @"quitMenu": @"Quitter GDrive Backup Tiger",
        @"settingsTitle": @"Réglages",
        @"languageSetting": @"Langue",
        @"cancel": @"Annuler",
        @"done": @"Terminé",
        @"languageSaved": @"Langue enregistrée.",
        @"overviewSubtitle": @"Copie indépendante · état clair · restauration prête",
        @"overviewLastRun": @"Dernière sauvegarde",
        @"overviewNextRun": @"Prochaine exécution",
        @"overviewTarget": @"Destination",
        @"overviewStorage": @"Stockage",
        @"overviewSettings": @"Configurer la sauvegarde …",
        @"overviewOpen": @"Ouvrir GDrive Backup Tiger",
        @"overviewNeverRun": @"Aucune sauvegarde",
        @"overviewUnavailable": @"Indisponible",
        @"overviewFreeOf": @"%@ libres sur %@",
        @"overviewStatusInterrupted": @"La sauvegarde a été interrompue.",
        @"overviewStatusUnknown": @"État de sauvegarde inconnu."
    };
    NSDictionary<NSString *, NSString *> *es = @{
        @"confirmTarget": @"¿Usar este volumen?",
        @"startBackup": @"Iniciar copia",
        @"notNow": @"Ahora no",
        @"running": @"Copia en curso ...",
        @"completed": @"Copia completada.",
        @"runningHint": @"No expulses el disco.",
        @"completedHint": @"La copia esta lista.",
        @"backupProgress": @"Progreso de la copia",
        @"failed": @"La copia ha fallado.",
        @"failedHint": @"No se creó una copia completa. Revisa el registro.",
        @"failedPermissionHint": @"No se puede escribir en el destino. Revisa los permisos del NAS.",
        @"cancelled": @"Copia cancelada.",
        @"cancelledHint": @"No se confirmó una finalización correcta.",
        @"skipped": @"No se inició una copia nueva.",
        @"skippedHint": @"Ya hay una copia en curso.",
        @"setupTitle": @"Destino y modo de inicio",
        @"targetType": @"Destino app/programado",
        @"destinationPreview": @"Destino exacto",
        @"externalVolume": @"Disco externo",
        @"encryptionAPFS": @"Exigir APFS cifrado (ya desbloqueado)",
        @"encryptionAPFSTip": @"La app no lee ni guarda ninguna contraseña.",
        @"nas": @"NAS / Red",
        @"mountedNas": @"NAS montado",
        @"refresh": @"Actualizar",
        @"discover": @"Buscar",
        @"openFinder": @"Abrir en Finder",
        @"nasUrl": @"URL del NAS",
        @"nasMount": @"Punto de montaje",
        @"nasSubdir": @"Carpeta destino",
        @"schedule": @"Inicio",
        @"scheduleManual": @"Solo manual",
        @"scheduleLogin": @"Al iniciar sesión",
        @"scheduleHourly": @"Cada hora",
        @"scheduleDaily": @"Diario 20:00",
        @"save": @"Guardar",
        @"dryRun": @"Comprobar copia",
        @"backupNow": @"Copiar ahora",
        @"dryRunTip": @"Comprueba origen y destino sin copiar archivos.",
        @"backupNowTip": @"Inicia la copia real hacia el destino elegido.",
        @"statusReady": @"Listo.",
        @"statusSaved": @"Guardado.",
        @"statusSearching": @"Buscando en la red ...",
        @"statusDiscoveryDone": @"Búsqueda de red completada.",
        @"statusBackupStarted": @"Copia iniciada.",
        @"statusBackupPreparing": @"Preparando la copia…",
        @"statusDryRunStarted": @"Comprobación iniciada. No se copiarán archivos.",
        @"statusUnsavedChanges": @"Guarda primero los cambios. No se inició ninguna copia.",
        @"selectMountedVolume": @"Seleccionar volumen",
        @"aboutMenu": @"Acerca de GDrive Backup Tiger",
        @"settingsMenu": @"Configuración ...",
        @"hideMenu": @"Ocultar GDrive Backup Tiger",
        @"quitMenu": @"Salir de GDrive Backup Tiger",
        @"settingsTitle": @"Configuración",
        @"languageSetting": @"Idioma",
        @"cancel": @"Cancelar",
        @"done": @"Listo",
        @"languageSaved": @"Idioma guardado.",
        @"overviewSubtitle": @"Copia independiente · estado claro · lista para restaurar",
        @"overviewLastRun": @"Última copia",
        @"overviewNextRun": @"Próxima ejecución",
        @"overviewTarget": @"Destino",
        @"overviewStorage": @"Almacenamiento",
        @"overviewSettings": @"Configurar copia …",
        @"overviewOpen": @"Abrir GDrive Backup Tiger",
        @"overviewNeverRun": @"Aún no hay copia",
        @"overviewUnavailable": @"No disponible",
        @"overviewFreeOf": @"%@ libres de %@",
        @"overviewStatusInterrupted": @"La copia fue interrumpida.",
        @"overviewStatusUnknown": @"Estado de copia desconocido."
    };
    NSDictionary<NSString *, NSString *> *ja = @{
        @"confirmTarget": @"このボリュームを使いますか？",
        @"startBackup": @"バックアップ開始",
        @"notNow": @"今はしない",
        @"running": @"バックアップ中...",
        @"completed": @"バックアップ完了。",
        @"runningHint": @"ディスクを取り出さないでください。",
        @"completedHint": @"完了しました。",
        @"backupProgress": @"バックアップの進行状況",
        @"failed": @"バックアップに失敗しました。",
        @"failedHint": @"完全なバックアップは作成されていません。ログを確認してください。",
        @"failedPermissionHint": @"保存先に書き込めません。NASの権限を確認してください。",
        @"cancelled": @"バックアップをキャンセルしました。",
        @"cancelledHint": @"正常終了は確認されていません。",
        @"skipped": @"新しいバックアップは開始されませんでした。",
        @"skippedHint": @"バックアップはすでに実行中です。",
        @"setupTitle": @"バックアップ先と開始方法",
        @"targetType": @"アプリ/スケジュール先",
        @"destinationPreview": @"正確な保存先",
        @"externalVolume": @"外部ディスク",
        @"encryptionAPFS": @"暗号化APFSを必須にする（ロック解除済み）",
        @"encryptionAPFSTip": @"このアプリはパスワードを読み取ったり保存したりしません。",
        @"nas": @"NAS / ネットワーク",
        @"mountedNas": @"マウント済みNAS",
        @"refresh": @"更新",
        @"discover": @"検索",
        @"openFinder": @"Finderで開く",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"マウント先",
        @"nasSubdir": @"保存先フォルダ",
        @"schedule": @"開始",
        @"scheduleManual": @"手動のみ",
        @"scheduleLogin": @"ログイン時",
        @"scheduleHourly": @"毎時",
        @"scheduleDaily": @"毎日 20:00",
        @"save": @"保存",
        @"dryRun": @"バックアップ確認",
        @"backupNow": @"今すぐバックアップ",
        @"dryRunTip": @"ファイルをコピーせず、元と保存先を確認します。",
        @"backupNowTip": @"選択した保存先へ実際のバックアップを開始します。",
        @"statusReady": @"準備完了。",
        @"statusSaved": @"保存しました。",
        @"statusSearching": @"ネットワーク検索中...",
        @"statusDiscoveryDone": @"ネットワーク検索完了。",
        @"statusBackupStarted": @"バックアップを開始しました。",
        @"statusBackupPreparing": @"バックアップを準備中…",
        @"statusDryRunStarted": @"確認を開始しました。ファイルはコピーされません。",
        @"statusUnsavedChanges": @"先に変更を保存してください。バックアップは開始されていません。",
        @"selectMountedVolume": @"ボリュームを選択",
        @"aboutMenu": @"GDrive Backup Tigerについて",
        @"settingsMenu": @"設定...",
        @"hideMenu": @"GDrive Backup Tigerを隠す",
        @"quitMenu": @"GDrive Backup Tigerを終了",
        @"settingsTitle": @"設定",
        @"languageSetting": @"言語",
        @"cancel": @"キャンセル",
        @"done": @"完了",
        @"languageSaved": @"言語を保存しました。",
        @"overviewSubtitle": @"独立したコピー · 明確な状態 · すぐに復元",
        @"overviewLastRun": @"前回のバックアップ",
        @"overviewNextRun": @"次回の実行",
        @"overviewTarget": @"保存先",
        @"overviewStorage": @"ストレージ",
        @"overviewSettings": @"バックアップを設定…",
        @"overviewOpen": @"GDrive Backup Tigerを開く",
        @"overviewNeverRun": @"バックアップはまだありません",
        @"overviewUnavailable": @"利用できません",
        @"overviewFreeOf": @"%@ 空き / %@",
        @"overviewStatusInterrupted": @"バックアップが中断されました。",
        @"overviewStatusUnknown": @"バックアップ状態は不明です。"
    };
    NSDictionary<NSString *, NSString *> *yue = @{
        @"confirmTarget": @"使用呢個卷宗？",
        @"startBackup": @"開始備份",
        @"notNow": @"暫時唔好",
        @"running": @"正在備份...",
        @"completed": @"備份完成。",
        @"runningHint": @"請勿退出磁碟。",
        @"completedHint": @"備份已完成。",
        @"backupProgress": @"備份進度",
        @"failed": @"備份失敗。",
        @"failedHint": @"未建立完整備份，請檢查記錄。",
        @"failedPermissionHint": @"無法寫入備份目的地，請檢查 NAS 權限。",
        @"cancelled": @"備份已取消。",
        @"cancelledHint": @"未確認成功完成。",
        @"skipped": @"未開始新備份。",
        @"skippedHint": @"備份已經進行中。",
        @"setupTitle": @"備份目的地同啟動方式",
        @"targetType": @"App/排程目的地",
        @"destinationPreview": @"確實目的地",
        @"externalVolume": @"外置磁碟",
        @"encryptionAPFS": @"要求加密 APFS（已解鎖）",
        @"encryptionAPFSTip": @"App 唔會讀取或儲存任何密碼。",
        @"nas": @"NAS / 網絡",
        @"mountedNas": @"已掛載 NAS",
        @"refresh": @"重新整理",
        @"discover": @"搜尋",
        @"openFinder": @"喺 Finder 開啟",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"掛載點",
        @"nasSubdir": @"目的地資料夾",
        @"schedule": @"啟動",
        @"scheduleManual": @"只限手動",
        @"scheduleLogin": @"登入時",
        @"scheduleHourly": @"每小時",
        @"scheduleDaily": @"每日 20:00",
        @"save": @"儲存",
        @"dryRun": @"檢查備份",
        @"backupNow": @"即刻備份",
        @"dryRunTip": @"只檢查來源同目的地，唔會複製檔案。",
        @"backupNowTip": @"開始真正備份到已選目的地。",
        @"statusReady": @"準備好。",
        @"statusSaved": @"已儲存。",
        @"statusSearching": @"搜尋網絡中...",
        @"statusDiscoveryDone": @"網絡搜尋完成。",
        @"statusBackupStarted": @"備份已開始。",
        @"statusBackupPreparing": @"正在準備備份…",
        @"statusDryRunStarted": @"檢查已開始。唔會複製檔案。",
        @"statusUnsavedChanges": @"請先儲存變更，未有開始備份。",
        @"selectMountedVolume": @"選擇卷宗",
        @"aboutMenu": @"關於 GDrive Backup Tiger",
        @"settingsMenu": @"設定...",
        @"hideMenu": @"隱藏 GDrive Backup Tiger",
        @"quitMenu": @"結束 GDrive Backup Tiger",
        @"settingsTitle": @"設定",
        @"languageSetting": @"語言",
        @"cancel": @"取消",
        @"done": @"完成",
        @"languageSaved": @"語言已儲存。",
        @"overviewSubtitle": @"獨立副本 · 狀態清楚 · 隨時可還原",
        @"overviewLastRun": @"上次備份",
        @"overviewNextRun": @"下次執行",
        @"overviewTarget": @"目的地",
        @"overviewStorage": @"儲存空間",
        @"overviewSettings": @"設定備份…",
        @"overviewOpen": @"開啟 GDrive Backup Tiger",
        @"overviewNeverRun": @"仲未有備份",
        @"overviewUnavailable": @"無法使用",
        @"overviewFreeOf": @"%@ 可用，共 %@",
        @"overviewStatusInterrupted": @"備份已中斷。",
        @"overviewStatusUnknown": @"備份狀態不明。"
    };
    NSDictionary<NSString *, NSString *> *ko = @{
        @"confirmTarget": @"이 볼륨을 사용할까요?",
        @"startBackup": @"백업 시작",
        @"notNow": @"지금 안 함",
        @"running": @"백업 중...",
        @"completed": @"백업 완료.",
        @"runningHint": @"디스크를 꺼내지 마세요.",
        @"completedHint": @"백업이 완료되었습니다.",
        @"backupProgress": @"백업 진행률",
        @"failed": @"백업에 실패했습니다.",
        @"failedHint": @"완전한 백업이 생성되지 않았습니다. 로그를 확인하세요.",
        @"failedPermissionHint": @"대상에 쓸 수 없습니다. NAS 권한을 확인하세요.",
        @"cancelled": @"백업이 취소되었습니다.",
        @"cancelledHint": @"성공적인 완료가 확인되지 않았습니다.",
        @"skipped": @"새 백업을 시작하지 않았습니다.",
        @"skippedHint": @"백업이 이미 실행 중입니다.",
        @"setupTitle": @"백업 대상 및 시작 방식",
        @"targetType": @"앱/예약 대상",
        @"destinationPreview": @"정확한 대상",
        @"externalVolume": @"외장 디스크",
        @"encryptionAPFS": @"암호화된 APFS 필요(이미 잠금 해제됨)",
        @"encryptionAPFSTip": @"앱은 암호를 읽거나 저장하지 않습니다.",
        @"nas": @"NAS / 네트워크",
        @"mountedNas": @"마운트된 NAS",
        @"refresh": @"새로 고침",
        @"discover": @"검색",
        @"openFinder": @"Finder에서 열기",
        @"nasUrl": @"NAS URL",
        @"nasMount": @"마운트 지점",
        @"nasSubdir": @"대상 폴더",
        @"schedule": @"시작",
        @"scheduleManual": @"수동만",
        @"scheduleLogin": @"로그인 시",
        @"scheduleHourly": @"매시간",
        @"scheduleDaily": @"매일 20:00",
        @"save": @"저장",
        @"dryRun": @"백업 확인",
        @"backupNow": @"지금 백업",
        @"dryRunTip": @"파일을 복사하지 않고 원본과 대상을 확인합니다.",
        @"backupNowTip": @"선택한 대상에 실제 백업을 시작합니다.",
        @"statusReady": @"준비됨.",
        @"statusSaved": @"저장됨.",
        @"statusSearching": @"네트워크 검색 중...",
        @"statusDiscoveryDone": @"네트워크 검색 완료.",
        @"statusBackupStarted": @"백업 시작됨.",
        @"statusBackupPreparing": @"백업 준비 중…",
        @"statusDryRunStarted": @"확인이 시작되었습니다. 파일은 복사되지 않습니다.",
        @"statusUnsavedChanges": @"먼저 변경 사항을 저장하세요. 백업은 시작되지 않았습니다.",
        @"selectMountedVolume": @"볼륨 선택",
        @"aboutMenu": @"GDrive Backup Tiger 정보",
        @"settingsMenu": @"설정...",
        @"hideMenu": @"GDrive Backup Tiger 가리기",
        @"quitMenu": @"GDrive Backup Tiger 종료",
        @"settingsTitle": @"설정",
        @"languageSetting": @"언어",
        @"cancel": @"취소",
        @"done": @"완료",
        @"languageSaved": @"언어가 저장되었습니다.",
        @"overviewSubtitle": @"독립 사본 · 명확한 상태 · 바로 복원",
        @"overviewLastRun": @"최근 백업",
        @"overviewNextRun": @"다음 실행",
        @"overviewTarget": @"대상",
        @"overviewStorage": @"저장 공간",
        @"overviewSettings": @"백업 설정…",
        @"overviewOpen": @"GDrive Backup Tiger 열기",
        @"overviewNeverRun": @"아직 백업 없음",
        @"overviewUnavailable": @"사용할 수 없음",
        @"overviewFreeOf": @"%@ 사용 가능 / %@",
        @"overviewStatusInterrupted": @"백업이 중단되었습니다.",
        @"overviewStatusUnknown": @"백업 상태를 알 수 없습니다."
    };

    NSDictionary<NSString *, NSDictionary<NSString *, NSString *> *> *tables = @{
        @"de": de,
        @"en": en,
        @"fr": fr,
        @"es": es,
        @"ja": ja,
        @"yue": yue,
        @"ko": ko
    };
    return (tables[language][key] ?: en[key]) ?: key;
}

NSArray<NSString *> *SupportedLanguageCodes(void) {
    return @[@"de", @"en", @"fr", @"es", @"ja", @"yue", @"ko"];
}

NSString *LanguageDisplayName(NSString *code) {
    NSDictionary<NSString *, NSString *> *names = @{
        @"de": @"Deutsch",
        @"en": @"English",
        @"fr": @"Français",
        @"es": @"Español",
        @"ja": @"日本語",
        @"yue": @"粵語",
        @"ko": @"한국어"
    };
    return names[code] ?: @"English";
}
